portraits =
{
	{'MAN1', 1},
	{'MAN2', 1},
	{'GENDWRF', 1},
	{'GENMELF', 1},
	{'GENMHLF', 1},
	{'NHORC', 1},
	{'AJANTIS', 1},
	{'CORAN', 1},
	{'EDWIN', 1},
	{'ELDOTH', 1},
	{'GARRICK', 1},
	{'KAGAIN', 1},
	{'KHALID', 1},
	{'KIVAN', 1},
	{'MINSC', 1},
	{'MONTAR', 1},
	{'QUAYLE', 1},
	{'TIAX', 1},
	{'XAN', 1},
	{'XZAR', 1},
	{'YESLICK', 1},
	{'RASAAD', 1},
	{'DORN',	1},
	{'BAELOTH',	1},
	{'GLINT',	1},
	{'VOGHILN',	1},
	{'NEDWIN', 1},
	{'NMINSC', 1},
	{'MANLEY0', 1},
	{'MANLEY3', 1},
	{'MANLEY6', 1},
	{'MANLEY7', 1},
	{'MANLEY8', 1},
	{'MANLEY9', 1},
	{'BDSHAM1L', 1},
	{'BDORCM1L', 1},
	{'WOMAN1', 2},
	{'WOMAN2', 2},
	{'ALORA', 2},
	{'BRANWE', 2},
	{'DYNAHEI', 2},
	{'FALDORN', 2},
	{'IMOEN', 2},
	{'BDIMOEN', 2},
	{'JAHEIRA', 2},
	{'SAFANA', 2},
	{'SHARTEL', 2},
	{'SKIE', 2},
	{'VICONIA', 2},
	{'BDVICON', 2},
	{'NEERA', 2},
	{'SCHAEL', 2},
	{'DSCLARA', 2},
	{'NJAHEIR', 2},
	{'NVICON', 2},
	{'MANLEY1', 2},
	{'MANLEY2', 2},
	{'MANLEY4', 2},
	{'MANLEY5', 2},
	{'MANLEYX', 2},
	{'BDSHAF1L', 2},
	{'BDORCF1L', 2}
}

movies = 
{
	{'intro', 1, 120, 32207, 0, 1},
	{'intro', 719, 779, 32166, 1, 1},
	{'intro', 809, 869, 32167, 0, 1},
	{'intro', 889, 959, 32168, 0, 1},
	{'intro', 949, 989, 32169, 1, 1},
	
	{'blackpit', 0, 89, 32170, 1, 1},
	{'blackpit', 119, 299, 32171, 1, 1},
	{'blackpit', 329, 389, 32172, 1, 1},
	{'blackpit', 449, 599, 32173, 1, 1},
	{'blackpit', 629, 719, 32174, 1, 1},
	
	--{'sodcin01', 10, 130, 62544, 1, 1},
	--{'sodcin01', 150, 280, 62545, 1, 1},
	--{'sodcin01', 300, 390, 62546, 1, 1},
	--{'sodcin01', 410, 520, 62547, 1, 1},
	--{'sodcin01', 540, 640, 62548, 1, 1},
	--{'sodcin01', 660, 830, 62549, 1, 1},
	--{'sodcin01', 850, 1030, 62550, 1, 1},
	--{'sodcin01', 1050, 1160, 62551, 1, 1},
	--{'sodcin01', 1180, 1330, 62552, 1, 1},
	--{'sodcin01', 1350, 1480, 62553, 1, 1},
	
	--{'sodcin02', 10, 200, 62554, 1, 1},
	--{'sodcin02', 260, 340, 62555, 1, 1},
	--{'sodcin02', 360, 420, 62556, 1, 1},
	--{'sodcin02', 440, 610, 62557, 1, 1},
	
	--{'sodcin03', 80, 150, 37711, 1, 1},
	--{'sodcin03', 190, 240, 37712, 1, 1},
	--{'sodcin03', 330, 400, 37713, 1, 1},
	--{'sodcin03', 420, 480, 37714, 1, 1},
	--{'sodcin03', 510, 600, 37715, 1, 1},
	--{'sodcin03', 620, 650, 37716, 1, 1},
	--{'sodcin03', 670, 710, 37717, 1, 1},
	--{'sodcin03', 730, 780, 37718, 1, 1}
}
credits =
{
    70379,
	24632,
	24633,
	24684,
	24685,
	24686,
	24687,
	32283,
	24701,	-- French Translation Team
	24702,	-- Spanish Translation Team
	24721,	-- German Translation Team
	24727,	-- Portuguese Brazilian Translation Team
	24705,	-- Polish Translation Team
	24713,  -- Italian Translation Team
	24707,	-- Czech Translation Team
	24719,	-- Turkish Translation Team
	24717,	-- Korean Translation Team
	24715,	-- Japanese Translation Team
	24709,	-- Chinese Simplified Team
	24688,	-- Original Interplay Bioware Credits
	24689,
	24690,
	24691,
	24692,
	24693,
	24694,
	24695,
	24696,
	24697,
	24700	-- Copy right notice
};

Infinity_AddDLC( 'dorn', 'DLCDN', 31092, 31093, 'BGEE_IOS_DORN', 'baldursgate_android_dorn' )
Infinity_AddDLC( 'neera', 'DLCNE', 31090, 31091, 'BGEE_IOS_NEERA', 'baldursgate_android_neera' )
Infinity_AddDLC( 'manley', 'DLCP1', 31094, 31095, 'BGEE_IOS_PORTRAITPACK1', 'baldursgate_android_portraitpack1' )
Infinity_AddDLC( 'voice', 'DLCV1', 31096, 31097, 'BGEE_IOS_VOICEPACK1', 'baldursgate_android_voicepack1' )

Infinity_AddDLCContent('FEMALE4', 4 )
Infinity_AddDLCContent('FEMALE5', 4 )
Infinity_AddDLCContent('FEMALE6', 4 )
Infinity_AddDLCContent('MALE4', 4 )
Infinity_AddDLCContent('MALE5', 4 )
Infinity_AddDLCContent('MALE6', 4 )
Infinity_AddDLCContent('DORN', 1 )
Infinity_AddDLCContent('NEERA', 2 )
Infinity_AddDLCContent('MANLEY0', 3 )
Infinity_AddDLCContent('MANLEY1', 3 )
Infinity_AddDLCContent('MANLEY2', 3 )
Infinity_AddDLCContent('MANLEY3', 3 )
Infinity_AddDLCContent('MANLEY4', 3 )
Infinity_AddDLCContent('MANLEY5', 3 )
Infinity_AddDLCContent('MANLEY6', 3 )
Infinity_AddDLCContent('MANLEY7', 3 )
Infinity_AddDLCContent('MANLEY8', 3 )
Infinity_AddDLCContent('MANLEY9', 3 )
Infinity_AddDLCContent('MANLEYX', 3 )

keybindings = 
{
	{
		{ 1,	1,	'Inventory',				"ASSIGN_KEYS_PAGE_INVENTORY",				'',		0,	105 },
		{ 2,	1,	'Character Record',			"ASSIGN_KEYS_PAGE_CHARACTERINFORMATION",	'',		0,	114 },
		{ 3,	1,	'Return To Game',			"ASSIGN_KEYS_PAGE_RETURNTOGAME",			'',		0,	103 },
		{ 4,	1,	'Journal',					"ASSIGN_KEYS_PAGE_JOURNAL",					'',		0,	106 },
		{ 5,	1,	'Map',						"ASSIGN_KEYS_PAGE_AREAMAP",					'',		0,	109 },
		{ 6,	1,	'Wizard Spells',			"ASSIGN_KEYS_PAGE_MAGESPELLS",				'',		0,	119 },
		{ 7,	1,	'Priest Spells',			"ASSIGN_KEYS_PAGE_PRIESTSPELLS",			'',		0,	112 },
		{ 8,	1,	'Options',					"ASSIGN_KEYS_PAGE_OPTIONS",					'',		0,	111 },
		{ 9,	1,	'Character Arbitration',	"ASSIGN_KEYS_PAGE_CHARACTERARBITRATION",	'',		0,	99 }
	},
	{
		{ 10,	2,	'Guard / Protect',			"ASSIGN_KEYS_ACTIONS_GUARD",				'',		0,	0 },
		{ 11,	2,	'Turn Undead',				"ASSIGN_KEYS_ACTIONS_TURNUNDEAD",			'',		0,	0 },
		{ 12, 2,	'Battle Song',				"ASSIGN_KEYS_ACTIONS_BARDSONG",				'',		0,	0 },
		{ 13, 2,	'Cast Spell',				"ASSIGN_KEYS_ACTIONS_CASTSPELL",			'',		0,	0 },
		{ 14, 2,	'Use Item',					"ASSIGN_KEYS_ACTIONS_USEITEM",				'',		0,	0 },
		{ 15, 2,	'Dialog',					"ASSIGN_KEYS_ACTIONS_DIALOG",				'',		0,	0 },
		{ 16, 2,	'Thieving',					"ASSIGN_KEYS_ACTIONS_THIEVING",				'',		0,	0 },
		{ 17, 2,	'Stealth',					"ASSIGN_KEYS_ACTIONS_STEALTH",				'',		0,	0 },
		{ 18, 2,	'Trap Detection',			"ASSIGN_KEYS_ACTIONS_FINDTRAPS",			'',		0,	0 },
		{ 19, 2,	'Group Stop',				"ASSIGN_KEYS_ACTIONS_GROUPSTOP",			'',		0,	0 },
		{ 20, 2,	'Group Attack',				"ASSIGN_KEYS_ACTIONS_GROUPATTACK",			'',		0,	0 },
		{ 21, 2,	'Special Abilities',		"ASSIGN_KEYS_ACTIONS_SPECIALABILITIES",		'',		0,	0 },
		{ 22, 2,	'Equip Melee Weapon',		"ASSIGN_KEYS_ACTIONS_EQUIPMELEEWEAPON",		'',		0,	0 },
		{ 23, 2,	'Equip Range Weapon',		"ASSIGN_KEYS_ACTIONS_EQUIPRANGEDWEAPON",	'',		0,	0 }
	},
	{
		{ 24, 3,	'Quick Load',				"ASSIGN_KEYS_MISC_QUICKLOAD",		'',		0,	108 },
		{ 25, 3,	'Hide Interface',			"ASSIGN_KEYS_MISC_HIDEINTERFACE",	'',		0,	104 },
		{ 26, 3,	'Right Interface',			"ASSIGN_KEYS_MISC_RIGHTINTERFACE",	'',		0,	117 },
		{ 27, 3,	'Chat Window',				"ASSIGN_KEYS_MISC_CHATWINDOW",		'',		0,	116 },
		{ 28, 3,	'Location',					"ASSIGN_KEYS_MISC_LOCATION",		'',		0,	120 },
		{ 29, 3,	'Quick Save',				"ASSIGN_KEYS_MISC_QUICKSAVE",		'',		0,	113 },
		{ 30, 3,	'Toggle AI',				"ASSIGN_KEYS_MISC_TOGGLEAI",		'',		0,	97 },
		{ 31, 3,	'Left Interface',			"ASSIGN_KEYS_MISC_LEFTINTERFACE",	'',		0,	121 },
		{ 32, 3,	'Rest',						"ASSIGN_KEYS_MISC_REST",			'',		0,	0 },
		{ 33, 3,	'Hard Pause',				"ASSIGN_KEYS_MISC_HARDPAUSE",		'',		0,	0 },
		{ 190, 3,   'Scroll Up',				"ASSIGN_KEYS_MISC_SCROLLUP",		'',		0,	0 },
		{ 193, 3,   'Scroll Left',				"ASSIGN_KEYS_MISC_SCROLLLEFT",		'',		0,	0 },
		{ 192, 3,   'Scroll Down',				"ASSIGN_KEYS_MISC_SCROLLDOWN",		'',		0,	0 },
		{ 191, 3,   'Scroll Right',				"ASSIGN_KEYS_MISC_SCROLLRIGHT",		'',		0,	0 }
	},
	{
		{ 34,	4,	'Spell Slot 1',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT1",		'',		0,	0 },
		{ 35,	4,	'Spell Slot 2',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT2",		'',		0,	0 },
		{ 36,	4,	'Spell Slot 3',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT3",		'',		0,	0 },
		{ 37,	4,	'Weapon Slot 1',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT1",		'',		0,	0 },
		{ 38,	4,	'Weapon Slot 2',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT2",		'',		0,	0 },
		{ 39,	4,	'Weapon Slot 3',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT3",		'',		0,	0 },
		{ 40,	4,	'Weapon Slot 4',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT4",		'',		0,	0 },
		{ 41,	4,	'Item Slot 1',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT1",			'',		0,	0 },
		{ 42,	4,	'Item Slot 2',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT2",			'',		0,	0 },
		{ 43,	4,	'Item Slot 3',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT3",			'',		0,	0 },
		{ 44,	4,	'Formation Slot 1',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT1",	'',		0,	0 },
		{ 45,	4,	'Formation Slot 2',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT2",	'',		0,	0 },
		{ 46,	4,	'Formation Slot 3',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT3",	'',		0,	0 },
		{ 47,	4,	'Formation Slot 4',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT4",	'',		0,	0 },
		{ 48,	4,	'Formation Slot 5',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT5",	'',		0,	0 },
		{ 176, 4, 'Character 1',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER1",  		'',		0,	49 },
		{ 177, 4, 'Character 2',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER2",  		'',		0,	50 },
		{ 178, 4, 'Character 3',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER3",  		'',		0,	51 },
		{ 179, 4, 'Character 4',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER4",  		'',		0,	52 },
		{ 180, 4, 'Character 5',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER5",  		'',		0,	53 },
		{ 181, 4, 'Character 6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER6",  		'',		0,	54 },
		{ 182, 4, 'Characters 1&2',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS12",  	'',		0,	55 },
		{ 183, 4, 'Characters 3&4',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS34",  	'',		0,	56 },
		{ 184, 4, 'Characters 5&6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS56",  	'',		0,	57 },
		{ 185, 4, 'Select 1,2,3',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS123",  	'',		0,	0 },
		{ 186, 4, 'Select 4,5,6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS456",  	'',		0,	0 },
		{ 187, 4, 'Select all',					"ASSIGN_KEYS_QUICKSLOTS_SELECTALL",  		'',		0,	48 },
		{ 188, 4, 'Zoom In',					"ASSIGN_KEYS_QUICKSLOTS_ZOOMIN",  			'',		0,	61 },
		{ 189, 4, 'Zoom Out',					"ASSIGN_KEYS_QUICKSLOTS_ZOOMOUT",  			'',		0,	45 }
	},
	{
		{ 49, 5,	'SPPR101',					12089,  '',     0,	0 },
		{ 50, 5,  'SPPR102',					12097,  '',		0,	0 },
		{ 51, 5,  'SPPR103',					12110,  '',		0,	0 },
		{ 52, 5,  'SPPR104',					12041,  '',		0,	0 },
		{ 53, 5,  'SPPR105',					12119,	'',		0,	0 },
		{ 54,	5,  'SPPR106',					12098,  '',     0,	0 },
		{ 55, 5,  'SPPR107',					12023,  '',     0,	0 },
		{ 56, 5,  'SPPR108',					12083,  '',     0,	0 },
		{ 57, 5,  'SPPR109',					12084,  '',		0,	0 },
		{ 58, 5,  'SPPR110',					12118,	'',		0,	0 },
		{ 59, 5,  'SPPR201',					12111,  '',     0,	0 },
		{ 60,	5,	'SPPR202',					12121,  '',		0,	0 },
		{ 61, 5,  'SPPR203',					12090,	'',		0,	0 },
		{ 62,	5,	'SPPR204',					12099,	'',		0,	0 },
		{ 63,	5,	'SPPR205',					12094,	'',		0,	0 },
		{ 64,	5,	'SPPR206',					12105,	'',		0,	0 },
		{ 65, 5,	'SPPR207',					12106,	'',		0,	0 },
		{ 66,	5,	'SPPR208',					12049,	'',		0,	0 },
		{ 67,	5,	'SPPR209',					12043,	'',		0,	0 },
		{ 68,	5,	'SPPR210',					12122,	'',		0,	0 },
		{ 69,	5,	'SPPR211',					12123,	'',		0,	0 },
		{ 70,	5,	'SPPR212',					12112,	'',		0,	0 },
		{ 71,	5,	'SPPR213',					12107,	'',		0,	0 },
		{ 72,	5,	'SPPR214',					12108,	'',		0,	0 },
		{ 73,	5,	'SPPR301',					12073,	'',		0,	0 },
		{ 74,	5,	'SPPR302',					12124,	'',		0,	0 },
		{ 75,	5,	'SPPR304',					12085,	'',		0,	0 },
		{ 76,	5,	'SPPR305',					12100,	'',		0,	0 },
		{ 77,	5,	'SPPR306',					12086,	'',		0,	0 },
		{ 78,	5,	'SPPR307',					12087,	'',		0,	0 },
		{ 79,	5,	'SPPR308',					12088,	'',		0,	0 },
		{ 80, 5,	'SPPR309',					12095,	'',		0,	0 },
		{ 81,	5,	'SPPR310',					12103,	'',		0,	0 },
		{ 82,	5,	'SPPR311',					12101,	'',		0,	0 },
		{ 83,	5,	'SPPR312',					12125,	'',		0,	0 },
		{ 84,	5,	'SPPR401',					12114,	'',		0,	0 },
		{ 85,	5,	'SPPR402',					12091,	'',		0,	0 },
		{ 86,	5,	'SPPR403',					12102,	'',		0,	0 },
		{ 87,	5,	'SPPR404',					12115,	'',		0,	0 },
		{ 88,	5,	'SPPR405',					22618,	'',		0,	0 },
		{ 89, 5,	'SPPR406',					22829,	'',		0,	0 },
		{ 90,	5,	'SPPR407',					22620,	'',		0,	0 },
		{ 91,	5,	'SPPR408',					12014,	'',		0,	0 },
		{ 92,	5,	'SPPR501',					12092,	'',		0,	0 },
		{ 93,	5,	'SPPR502',					12092,	'',		0,	0 },
		{ 94,	5,	'SPPR503',					12109,	'',		0,	0 },
		{ 95,	5,	'SPPR504',					12117,	'',		0,	0 },
		{ 96,	5,	'SPPR506',					22833,	'',		0,	0 },
		{ 97,	5,	'SPPR508',					22903,	'',		0,	0 }
	},
	{
		{ 98,	6,	'SPWI101',					12030,	'',		0,	0 },
		{ 99,	6,	'SPWI102',					12031,	'',		0,	0 },
		{ 100, 6, 'SPWI103',					12074,	'',		0,	0 },
		{ 101, 6, 'SPWI104',					12045,	'',		0,	0 },
		{ 102, 6, 'SPWI105',					12075,	'',		0,	0 },
		{ 103, 6, 'SPWI106',					12015,	'',		0,	0 },
		{ 104, 6, 'SPWI107',					12046,	'',		0,	0 },
		{ 105, 6, 'SPWI108',					12024,	'',		0,	0 },
		{ 106, 6, 'SPWI111',					12039,	'',		0,	0 },
		{ 107, 6, 'SPWI112',					12052,	'',		0,	0 },
		{ 108, 6, 'SPWI113',					12023,	'',		0,	0 },
		{ 109, 6, 'SPWI114',					12053,	'',		0,	0 },
		{ 110, 6, 'SPWI115',					12076,	'',		0,	0 },
		{ 111, 6, 'SPWI116',					12047,	'',		0,	0 },
		{ 112, 6, 'SPWI117',					12067,	'',		0,	0 },
		{ 113, 6, 'SPWI118',					12054,	'',		0,	0 },
		{ 114, 6, 'SPWI119',					12068,	'',		0,	0 },
		{ 115, 6, 'SPWI201',					12016,	'',		0,	0 },
		{ 116, 6, 'SPWI202',					12041,	'',		0,	0 },
		{ 117, 6, 'SPWI203',					12042,	'',		0,	0 },
		{ 118, 6, 'SPWI205',					12069,	'',		0,	0 },
		{ 119, 6, 'SPWI206',					12017,	'',		0,	0 },
		{ 120, 6, 'SPWI207',					12131,	'',		0,	0 },
		{ 121, 6, 'SPWI208',					12043,	'',		0,	0 },
		{ 122, 6, 'SPWI209',					12048,	'',		0,	0 },
		{ 123, 6, 'SPWI210',					12025,	'',		0,	0 },
		{ 124, 6, 'SPWI211',					12033,	'',		0,	0 },
		{ 125, 6, 'SPWI212',					12018,	'',		0,	0 },
		{ 126, 6, 'SPWI213',					12056,	'',		0,	0 },
		{ 127, 6, 'SPWI214',					12077,	'',		0,	0 },
		{ 128, 6, 'SPWI215',					12057,	'',		0,	0 },
		{ 129, 6, 'SPWI217',					12058,	'',		0,	0 },
		{ 130, 6, 'SPWI218',					12070,	'',		0,	0 },
		{ 131, 6, 'SPWI219',					12079,	'',		0,	0 },
		{ 132, 6, 'SPWI301',					12044,	'',		0,	0 },
		{ 133, 6, 'SPWI302',					12026,	'',		0,	0 },
		{ 134, 6, 'SPWI303',					12034,	'',		0,	0 },
		{ 135, 6, 'SPWI304',					6618,	'',		0,	0 },
		{ 136, 6, 'SPWI305',					12080,	'',		0,	0 },
		{ 137, 6, 'SPWI306',					12049,	'',		0,	0 },
		{ 138, 6, 'SPWI308',					12060,	'',		0,	0 },
		{ 139, 6, 'SPWI309',					12035,	'',		0,	0 },
		{ 140, 6, 'SPWI310',					12027,	'',		0,	0 },
		{ 141, 6, 'SPWI311',					12028,	'',		0,	0 },
		{ 142, 6, 'SPWI312',					12081,	'',     0,	0 },
		{ 143, 6, 'SPWI313',					12072,	'',		0,	0 },
		{ 144, 6, 'SPWI314',					12071,	'',		0,	0 },
		{ 145, 6, 'SPWI316',					12050,	'',		0,	0 },
		{ 146, 6, 'SPWI317',					12129,	'',		0,	0 },
		{ 147, 6, 'SPWI401',					12051,	'',		0,	0 },
		{ 148, 6, 'SPWI402',					12082,	'',		0,	0 },
		{ 149, 6, 'SPWI404',					12062,	'',		0,	0 },
		{ 150, 6, 'SPWI405',					12021,	'',		0,	0 },
		{ 151, 6, 'SPWI406',					12029,	'',		0,	0 },
		{ 152, 6, 'SPWI407',					12037,	'',		0,	0 },
		{ 153, 6, 'SPWI409',					12063,	'',		0,	0 },
		{ 154, 6, 'SPWI410',					12087,	'',		0,	0 },
		{ 155, 6, 'SPWI411',					22173,	'',		0,	0 },
		{ 156, 6, 'SPWI412',					22185,	'',		0,	0 },
		{ 157, 6, 'SPWI413',					22177,	'',		0,	0 },
		{ 158, 6, 'SPWI414',					22608,	'',		0,	0 },
		{ 159, 6, 'SPWI415',					20963,	'',		0,	0 },
		{ 160, 6, 'SPWI416',					22316,	'',		0,	0 },
		{ 161, 6, 'SPWI501',					12073,	'',		0,	0 },
		{ 162, 6, 'SPWI502',					12065,	'',		0,	0 },
		{ 163, 6, 'SPWI503',					12066,	'',		0,	0 },
		{ 164, 6, 'SPWI504',					12038,	'',		0,	0 },
		{ 165, 6, 'SPWI505',					12022,	'',		0,	0 },
		{ 167, 6, 'SPWI506',					22614,	'',		0,	0 },
		{ 168, 6, 'SPWI507',					22616,	'',		0,	0 },
		{ 169, 6, 'SPWI508',					22610,	'',		0,	0 },
		{ 170, 6, 'SPWI509',					22612,	'',		0,	0 },
		{ 171, 6, 'SPWI601',					23790,	'',		0,	0 },
		{ 172, 6, 'SPWI602',					23791,	'',		0,	0 },
		{ 173, 6, 'SPWI603',					23792,	'',		0,	0 },
		{ 174, 6, 'SPWI604',					23793,	'',		0,	0 },
		{ 175, 6, 'SPWI605',					24100,	'',		0,	0 }
	}
};
keycategories = 
{
	{ 1, "ASSIGN_KEYS_PAGE", 			'Keymap Page' },
	{ 2, "ASSIGN_KEYS_ACTIONS", 		'Keymap Action' },
	{ 3, "ASSIGN_KEYS_MISC", 			'Keymap Miscellaneous' },
	{ 4, "ASSIGN_KEYS_QUICKSLOTS", 		'Keymap Quick Slots' },
	{ 5, "ASSIGN_KEYS_PRIESTSPELLS",	'Priest Spells' },
	{ 6, "ASSIGN_KEYS_MAGESPELLS", 		'Mage Spells' }
};

languages = {
	{'zh_CN', 24709, 24710, 'Chinese'},
	{'cs_CZ', 24707, 24708, 'Èeština'},
	{'en_US', 24698, 24699, 'English'},
	{'fr_FR', 24701, 24704, 'Français'},
	{'de_DE', 24721, 24722, 'Deutsch'},
	{'it_IT', 24713, 24714, 'Italiano'},
	{'ja_JP', 24715, 24716, 'Japanese'},
	{'ko_KR', 24717, 24718, 'Korean'},
	{'pl_PL', 24705, 24706, 'Polski'},
	{'pt_BR', 24727, 24728, 'Portugu?s'},
	{'ru_RU', 24723, 24724, 'Russian'},
	{'es_ES', 24702, 24703, 'Espa?ol'},
	{'tr_TR', 24719, 24720, 'Türkçe'},
	{'uk_UA', 24725, 24726, 'Ukrainian'},
	{'hu_HU', 0, 0, 'Magyar'}
}

mp_sessions = {}
mp_sessions_jid = {}
mp_backend_type = 0
passwordMp = "password"

font_colors={}
--not from bgee. doesn't seem to be used in dragonspear:
-- font_colors['REALMS'] 	= '0xFFE2DDCF'
-- font_colors['NORMAL']	= '0xFF2C2121'
-- font_colors['STONESML']	= '0xFFCECECE'
-- font_colors['STONEBIG']	= '0xFFBCBCBC'
-- font_colors['INITIALS']	= '0xFFB98C00'

--from IWDEE, doesn't seem to be filled in for dragonspear
filenames_stringrefs={}
filenames_stringrefs['MALE1'] = {70656, 2}
filenames_stringrefs['MALE2'] = {70657, 2}
filenames_stringrefs['MALE3'] = {70658, 2}
filenames_stringrefs['MALE4'] = {70659, 2}
filenames_stringrefs['MALE5'] = {70660, 2}
filenames_stringrefs['MALE6'] = {70661, 2}
filenames_stringrefs['MALE7'] = {70662, 2}
filenames_stringrefs['MALE8'] = {70663, 2}
filenames_stringrefs['FEMALE1'] = {70665, 2}
filenames_stringrefs['FEMALE2'] = {70666, 2}
filenames_stringrefs['FEMALE3'] = {70667, 2}
filenames_stringrefs['FEMALE4'] = {70668, 2}
filenames_stringrefs['FEMALE5'] = {70669, 2}
filenames_stringrefs['FEMALE6'] = {70670, 2}
filenames_stringrefs['FEMALE7'] = {70671, 2}
filenames_stringrefs['FEMALE8'] = {70672, 2}

messageBoxMessageCount = 7
--TODO these should really become string refs.
-- CLOUD_SAVE_DOWNLOAD_FAILED,
-- CLOUD_SAVE_METADATA_WRITE_FAILED,
-- CLOUD_SAVE_METADATA_READ_FAILED,
-- CLOUD_SAVE_SNAPSHOT_LIST_DOWNLOAD_FAILED,
-- CLOUD_SAVE_CLOUD_READ_FAILED
-- CLOUD_SAVE_QUOTA_EXCEEDED
-- CLOUD_SAVE_FILE_TOO_LARGE	
messages = 
{
	'An error occurred while downloading a cloud save.',
	'An error occurred while writing a cloud save metadata file.',
	'An error occurred while reading a cloud save metadata file.',
	'An error occurred while downloading the list of cloud save files.',
	'An error occurred while uploading a cloud save.',
	'Your Steam cloud save storage quota has been exceeded.',
	'Save file is too large to upload to the Steam cloud.'
}

textflashes = {}
textflashidx = 1

cheatAreas = {
	{"BD0010", "Ducal Palace City Exterior"},
	{"BD0020", "Sorcerous/Elf Song City Exterior"},
	{"BD0030", "Flaming Fist City Exterior"},
	{"BD0040", "Three Kegs City Exterior"},
	{"BD0050", "Iron Throne City Exterior"},
	{"BD0060", "Random Area - Cave Entrance"},
	{"BD0061", "Random Area - Cave Interior from BD0060"},
	{"BD0062", "Random Area - Cave Pool from BD0061"},
	{"BD0063", "Random Area - Canyon Ambush"},
	{"BD0064", "Random Area - Forest Paths"},
	{"BD0065", "Random Area - Wilderness Open Area"},
	{"BD0066", "Random Area - Wilderness Hole to BD0067"},
	{"BD0067", "Random Area - Cave Interior from BD0066"},
	{"BD0070", "The Scrying Pool - The Hooded Man Cutscene"},
	{"BD0071", "The Scrying Pool - Caelar Cutscene"},
	{"BD0100", "Ducal Palace, Second Floor"},
	{"BD0101", "Ducal Palace, Leaving BG"},
	{"BD0102", "Ducal Palace, First Floor"},
	{"BD0103", "Ducal Palace, Third Floor"},
	{"BD0104", "Flaming Fist HQ"},
	{"BD0105", "Flaming Fist HQ, Basement"},
	{"BD0106", "Three Old Kegs, First Floor"},
	{"BD0107", "Three Old Kegs, Second Floor"},
	{"BD0108", "Three Old Kegs, Third Floor"},
	{"BD0109", "Elfsong Tavern, First Floor"},
	{"BD0110", "Elfsong Tavern, Second Floor"},
	{"BD0111", "Iron Throne Floor, First Floor"},
	{"BD0112", "Baldur's Gate East"},
	{"BD0113", "Underground Cavern Wyrms"},
	{"BD0114", "Spider Cave"},
	{"BD0115", "Vampire Cavern"},
	{"BD0116", "Ducal Palace, Basement"},
	{"BD0117", "Iron Throne, Basement"},
	{"BD0118", "The Scrying Pool - Imoen Cutscene"},
	{"BD0120", "Tomb Safehouse, First Floor"},
	{"BD0121", "Sorcerous Sundries, First Floor"},
	{"BD0122", "Sorcerous Sundries, Second Floor"},
	{"BD0130", "Tomb Safehouse, Second Floor"},
	{"BD1000", "Coast Way Crossing"},
	{"BD1010", "Cave (generic)"},
	{"BD1100", "The Dig"},
	{"BD1200", "Lich Outpost"},
	{"BD2000", "Boareskyr Bridge & Bridgefort"},
	{"BD2010", "Cave (generic)"},
	{"BD2100", "Bridgefort Interior"},
	{"BD3000", "Allied Siege Camp"},
	{"BD4000", "Dragonspear Castle, Exterior"},
	{"BD4100", "Dragonspear Castle Keep, First Floor"},
	{"BD4300", "Dragonspear Castle Basement"},
	{"BD4400", "Avernus"},
	{"BD4500", "Avernus Bridge"},
	{"BD4600", "Avernus Interior"},
	{"BD4601", "Avernus Elevator"},
	{"BD4700", "Avernus Roof"},
	{"BD5000", "Underground River Entrance"},
	{"BD5100", "Underground River"},
	{"BD5110", "Ettin Ghost Cave"},
	{"BD5200", "The Warrens"},
	{"BD5300", "Kanaglym"},
	{"BD6000", "Abandoned Sewers & Caverns"},
	{"BD6200", "Sewers Exit"},
	{"BD6100", "The Ambush"},
	{"BD7000", "Coast Way Forest"},
	{"BD7100", "Troll Forest"},
	{"BD7110", "Troll Cave"},
	{"BD7200", "Forest of Wyrms"},
	{"BD7210", "Wyrm Cave"},
	{"BD7220", "Bugbear Stronghold"},
	{"BD7230", "Temple of Cyric"},
	{"BD7300", "Dead Man's Pass"},
	{"BD7310", "Hidden Cellar/Treasure Stash"},
	{"BD7400", "Bloodbark Grove"},
	{"BD7410", "Vampire Hideout"},
}
fontcolors = {}
-- AABBGGRR
fontcolors['1'] = 'FFCAE2E9' -- title
fontcolors['2'] = 'FFCAE2E9' -- title highlight
fontcolors['3'] = 'FFCAE2E9' -- subtitle
fontcolors['4'] = 'FFEEFFFF' -- subtitle highlight
fontcolors['5'] = 'FF000000' -- parchment
fontcolors['6'] = 'FFEEFFFF' -- parchment highlight
fontcolors['7'] = 'FF000000' -- alternate parchment
fontcolors['8'] = 'FF102526' -- alternate parchment highlight
fontcolors['9'] = 'FFCDD6D9' -- semitrans dark background
fontcolors['A'] = 'FFFDE6E9' -- semitrans dark background highlight
fontcolors['B'] = 'FFCECECE'
fontcolors['C'] = 'FFC8F0C8' -- Minty update color
fontcolors['D'] = 'FF96C8FF' -- orangy subtitle color
fontcolors['R'] = 'FF0000FF' -- red
fontcolors['G'] = 'FF00FF00' -- green
fontcolors['M'] = 'FF000080' -- parchment red
fontcolors['$'] = 'FF82E6FF' -- gold yellow/orange
fontcolors['X'] = 'FF7D7D7D' -- gold yellow/orange

characters = {}

tempStats = {}

styles =
{
	gamelog =
	{
		color = 'B',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},

	normal =
	{
		color = 'B',
		font = 'MODESTOM',
		point = 14,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	rg_trajan =
	{
		color = '5',
		font = 'RGTRAJ',
		point = 14,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	normal_big =
	{
		color = 'B',
		font = 'MODESTOM',
		point = 18,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	normal_parchment =
	{
		color = '5',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	title =
	{
		color = '1',
		font = 'SHERWOOD',
		point = 20,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
	},
	parchment = 
	{
		color = '5',
		font = 'POSTANTI' ,
		point = 12,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	button =
	{
		color = 'B',
		font = 'MODESTOM' ,
		point = 18,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
		upper = 1,
		pad = {8,8,8,8},
	},
	label =
	{
		color = 'B',
		font = 'MODESTOM',
		point = 14,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
	},
	label_parchment =
	{
		color = '5',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
	},
	button_parchment =
	{
		color = '5',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
		pad = {0,5,0,0},
	},
	edit =
	{
		color = 'B',
		font = 'MODESTOM',
		point = 14,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	edit_parchment =
	{
		color = '5',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	list =
	{
		color = 'B',
		font = 'STONESML',
		point = 18,
		useFontZoom = 0,
		valign = 'center',
		halign = 'left',
	},
	list_parchment =
	{
		color = '5',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 0,
		valign = 'center',
		halign = 'left',
	},
	gold =
	{
		color = '$',
		font = 'MODESTOM',
		point = 12,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
	},
	label_loadname =
	{
		color = 'B',
		font = 'MODESTOM',
		point = 20,
		useFontZoom = 0,
		valign = 'center',
		halign = 'center',
	}
}

chapterBackgrounds = {}
chapterBackgrounds[0] = "GUICHP0A"
chapterBackgrounds[1] = "GUICHP1A"
chapterBackgrounds[2] = "GUICHP2A"
chapterBackgrounds[3] = "GUICHP3A"
chapterBackgrounds[4] = "GUICHP4A"
chapterBackgrounds[5] = "GUICHP5A"
chapterBackgrounds[6] = "GUICHP6A"
chapterBackgrounds[7] = "GUICHP7A"
chapterBackgrounds[8] = "GUICHP1B"
chapterBackgrounds[9] = "GUICHP2B"
chapterBackgrounds[10] = "GUICHP3B"
chapterBackgrounds[11] = "GUICHP4B"
chapterBackgrounds[12] = "GUICHP5B"
chapterBackgrounds[13] = "GUICHP6B"

chapterBackgrounds[20] = "BPEND"

chapterBackgrounds[52] = "GUIDRM2"
chapterBackgrounds[53] = "GUIDRM3"
chapterBackgrounds[54] = "GUIDRM4"
chapterBackgrounds[55] = "GUIDRM5"
chapterBackgrounds[56] = "GUIDRM6"
chapterBackgrounds[57] = "GUIDRM7"
chapterBackgrounds[58] = "ARRIVE"
chapterBackgrounds[59] = "LEAVE"

chapterBackgrounds[100] = "GUICHP6B"

const =
{
	ENTRY_TYPE_NONE = -1,
	ENTRY_TYPE_USER = 0,
	ENTRY_TYPE_INPROGRESS = 1,
	ENTRY_TYPE_COMPLETE = 2,
	ENTRY_TYPE_INFO = 4,
	
	ENTRIES_IDX_STRREF = 1,
	ENTRIES_IDX_QUEST = 2,
	ENTRIES_IDX_STATE = 3,
	ENTRIES_IDX_SUBGROUP = 4,
	ENTRIES_IDX_TIMESTAMP = 5,
	ENTRIES_IDX_RECV = 6,
	
	JOURNAL_STATE_USER  = 0,
	JOURNAL_STATE_INPROGRESS = 1,
	JOURNAL_STATE_COMPLETE = 2,
	JOURNAL_STATE_INFO = 4,
	
	QUEST_IDX_ID = 1,
	QUEST_IDX_STRREF = 3,
	QUEST_IDX_STATE = 5,
	QUEST_IDX_CHAPTER = 6,
	QUEST_IDX_RECV = 7,
	
	USER_IDX_STRREF = 1,
	USER_IDX_TIMESTAMP = 2,
	USER_IDX_STATE = 3,
	USER_IDX_CHAPTER = 4,
	USER_IDX_RECV = 5,
	
	INFO_IDX_STRREF = 1,
	INFO_IDX_TIMESTAMP = 2,
	INFO_IDX_STATE = 3,
	INFO_IDX_CHAPTER = 4,
	INFO_IDX_RECV = 5,
	
	IDX_IMPORTANT = 1,
		
	STEP_DUALCLASS_CLASS = 24,
	STEP_DUALCLASS_PROFICIENCIES = 25,
	STEP_DUALCLASS_DONE = 27,
	
	CUSTOMIZE_ID = 17,
	SCRIPT_ID = 11,
	EXPORT_ID = 13,
	SOUND_ID = 20,
	
	JOURNAL_MODE_QUESTS = 1,
	JOURNAL_MODE_JOURNAL = 2,
	JOURNAL_MODE_EDIT = 3,
	
	START_CAMPAIGN_BG = 1,
	START_CAMPAIGN_BP = 2,
	START_CAMPAIGN_SOD = 3,
	
	
}
function buildQuestsTable()
	Infinity_Log("Initializing Quests")
	quests = {}
	userNotes = {}
	subGroups = {}
	looseEntries = {}
	createQuest    ( 31270 )
	createEntry    ( 31270, -1, 31438, {}, nil )
	createEntry    ( 31270, -1, 31439, {}, nil )
	createEntry    ( 31270, -1, 31440, {}, nil )
	createEntry    ( 31270, -1, 31441, {}, nil )
	createEntry    ( 31270, -1, 31442, {}, nil )
	createEntry    ( 31270, -1, 31443, {}, nil )
	createEntry    ( 31270, -1, 31444, {}, nil )
	createEntry    ( 31270, -1, 31445, {}, nil )
	createEntry    ( 31270, -1, 31446, {}, nil )
	createEntry    ( 31270, -1, 31447, {}, nil )
	createEntry    ( 31270, -1, 31448, {}, nil )
	createEntry    ( 31270, -1, 31449, {}, nil )
	createEntry    ( 31270, -1, 31450, {}, nil )
	createEntry    ( 31270, -1, 31451, {}, nil )
	createEntry    ( 31270, -1, 31452, {}, nil )
	createEntry    ( 31270, -1, 31453, {}, nil )
	createEntry    ( 31270, -1, 31454, {}, nil )
	createEntry    ( 31270, -1, 31455, {}, nil )
	createEntry    ( 31270, -1, 31456, {}, nil )
	createEntry    ( 31270, -1, 31457, {}, nil )
	createEntry    ( 31270, -1, 31458, {}, nil )
	createEntry    ( 31270, -1, 31459, {}, nil )
	createEntry    ( 31270, -1, 31460, {}, nil )
	createEntry    ( 31270, -1, 31461, {}, nil )
	createEntry    ( 31270, -1, 31462, {}, nil )
	createEntry    ( 31270, -1, 31463, {}, nil )
	createEntry    ( 31270, -1, 31464, {}, nil )
	createEntry    ( 31270, -1, 31465, {}, nil )
	createEntry    ( 31270, -1, 31466, {}, nil )
	createEntry    ( 31270, -1, 31467, {}, nil )
	createEntry    ( 31270, -1, 31468, {}, nil )
	createEntry    ( 31270, -1, 31469, {}, nil )
	createEntry    ( 31270, -1, 31470, {}, nil )
	createEntry    ( 31270, -1, 31471, {}, nil )
	createEntry    ( 31270, -1, 31472, {}, nil )
	createEntry    ( 31270, -1, 31473, {}, nil )
	createEntry    ( 31270, -1, 31474, {}, nil )
	createEntry    ( 31270, -1, 31475, {}, nil )
	createEntry    ( 31270, -1, 32134, {}, nil )
	createEntry    ( 31270, -1, 56379, {}, 185 )
	createEntry    ( 31270, -1, 66955, {}, 185 )
	createEntry    ( 31270, -1, 66637, {}, 185 )
	createEntry    ( 31270, -1, 66638, {}, 185 )
	createEntry    ( 31270, -1, 59572, {}, 185 )
	createEntry    ( 31270, -1, 59573, {}, 185 )
	createEntry    ( 31270, -1, 66653, {}, 277 )
	createEntry    ( 31270, -1, 64565, {}, 277 )
	createEntry    ( 31270, -1, 64632, {}, 277 )
	createEntry    ( 31270, -1, 59617, {}, 280 )
	createEntry    ( 31270, -1, 66718, {}, 280 )
	createEntry    ( 31270, -1, 66719, {}, 280 )
	createEntry    ( 31270, -1, 61550, {}, 280 )
	createEntry    ( 31270, -1, 61552, {}, 280 )
	createEntry    ( 31270, -1, 61556, {}, 280 )
	createEntry    ( 31270, -1, 61563, {}, 280 )
	createEntry    ( 31270, -1, 61574, {}, 280 )
	createEntry    ( 31270, -1, 66840, {}, 280 )
	createEntry    ( 31270, -1, 67092, {}, 280 )
	createEntry    ( 31270, -1, 67093, {}, 280 )
	createEntry    ( 31270, -1, 67094, {}, 280 )
	createEntry    ( 31270, -1, 67095, {}, 280 )
	createEntry    ( 31270, -1, 67096, {}, 280 )
	createEntry    ( 31270, -1, 67097, {}, 280 )
	createEntry    ( 31270, -1, 67098, {}, 280 )
	createEntry    ( 31270, -1, 67099, {}, 280 )
	createEntry    ( 31270, -1, 66860, {}, 185 )
	createEntry    ( 31270, -1, 69087, {}, 185 )
	createEntry    ( 31270, -1, 59647, {}, 185 )
	createEntry    ( 31270, -1, 59648, {}, 185 )
	createEntry    ( 31270, -1, 59649, {}, 185 )
	createEntry    ( 31270, -1, 59650, {}, 185 )
	createEntry    ( 31270, -1, 59657, {}, 185 )
	createEntry    ( 31270, -1, 67020, {}, 185 )
	createEntry    ( 31270, -1, 67023, {}, 185 )
	createEntry    ( 31270, -1, 67025, {}, 185 )
	createEntry    ( 31270, -1, 67027, {}, 185 )
	createEntry    ( 31270, -1, 67029, {}, 185 )
	createEntry    ( 31270, -1, 67033, {}, 185 )
	createEntry    ( 31270, -1, 67035, {}, 185 )
	createEntry    ( 31270, -1, 67326, {}, 185 )
	createEntry    ( 31270, -1, 67329, {}, 185 )
	createEntry    ( 31270, -1, 69028, {}, 185 )
	createEntry    ( 31270, -1, 70598, {}, 185 )
	createEntry    ( 31270, -1, 66862, {}, 195 )
	createEntry    ( 31270, -1, 59708, {}, 195 )
	createEntry    ( 31270, -1, 59747, {}, 195 )
	createEntry    ( 31270, -1, 59762, {}, 195 )
	createEntry    ( 31270, -1, 65934, {}, 195 )
	createEntry    ( 31270, -1, 59766, {}, 195 )
	createEntry    ( 31270, -1, 59767, {}, 195 )
	createEntry    ( 31270, -1, 59768, {}, 195 )
	createEntry    ( 31270, -1, 59769, {}, 195 )
	createEntry    ( 31270, -1, 65083, {}, 195 )
	createEntry    ( 31270, -1, 59771, {}, 195 )
	createEntry    ( 31270, -1, 59772, {}, 195 )
	createEntry    ( 31270, -1, 65108, {}, 195 )
	createEntry    ( 31270, -1, 59773, {}, 195 )
	createEntry    ( 31270, -1, 67039, {}, 195 )
	createEntry    ( 31270, -1, 67041, {}, 195 )
	createEntry    ( 31270, -1, 67043, {}, 195 )
	createEntry    ( 31270, -1, 67047, {}, 195 )
	createEntry    ( 31270, -1, 67049, {}, 195 )
	createEntry    ( 31270, -1, 67051, {}, 195 )
	createEntry    ( 31270, -1, 67053, {}, 195 )
	createEntry    ( 31270, -1, 67055, {}, 195 )
	createEntry    ( 31270, -1, 67059, {}, 195 )
	createEntry    ( 31270, -1, 68949, {}, 195 )
	createEntry    ( 31270, -1, 64980, {}, 274 )
	createEntry    ( 31270, -1, 64984, {}, 274 )
	createEntry    ( 31270, -1, 64989, {}, 274 )
	createEntry    ( 31270, -1, 64182, {}, 274 )
	createEntry    ( 31270, -1, 67045, {}, 274 )
	createEntry    ( 31270, -1, 66689, {}, 274 )
	createEntry    ( 31270, -1, 66865, {}, 278 )
	createEntry    ( 31270, -1, 59777, {}, 278 )
	createEntry    ( 31270, -1, 59780, {}, 278 )
	createEntry    ( 31270, -1, 59792, {}, 278 )
	createEntry    ( 31270, -1, 65485, {}, 278 )
	createEntry    ( 31270, -1, 59793, {}, 278 )
	createEntry    ( 31270, -1, 59794, {}, 278 )
	createEntry    ( 31270, -1, 59795, {}, 278 )
	createEntry    ( 31270, -1, 65811, {}, 278 )
	createEntry    ( 31270, -1, 56558, {}, 278 )
	createEntry    ( 31270, -1, 56559, {}, 278 )
	createEntry    ( 31270, -1, 71117, {}, 278 )
	createEntry    ( 31270, -1, 67063, {}, 278 )
	createEntry    ( 31270, -1, 67067, {}, 278 )
	createEntry    ( 31270, -1, 67069, {}, 278 )
	createEntry    ( 31270, -1, 67071, {}, 278 )
	createEntry    ( 31270, -1, 67073, {}, 278 )
	createEntry    ( 31270, -1, 67075, {}, 278 )
	createEntry    ( 31270, -1, 67077, {}, 278 )
	createEntry    ( 31270, -1, 67079, {}, 278 )
	createEntry    ( 31270, -1, 67085, {}, 278 )
	createEntry    ( 31270, -1, 67087, {}, 278 )
	createEntry    ( 31270, -1, 67089, {}, 278 )
	createEntry    ( 31270, -1, 52053, {}, 278 )
	createEntry    ( 31270, -1, 59781, {}, 200 )
	createEntry    ( 31270, -1, 59784, {}, 200 )
	createEntry    ( 31270, -1, 63369, {}, 200 )
	createEntry    ( 31270, -1, 63370, {}, 200 )
	createEntry    ( 31270, -1, 63371, {}, 200 )
	createEntry    ( 31270, -1, 61943, {}, 200 )
	createEntry    ( 31270, -1, 67369, {}, 200 )
	createEntry    ( 31270, -1, 66742, {}, 279 )
	createEntry    ( 31270, -1, 59796, {}, 279 )
	createEntry    ( 31270, -1, 59797, {}, 279 )
	createEntry    ( 31270, -1, 66744, {}, 279 )
	createEntry    ( 31270, -1, 65412, {}, 279 )
	createEntry    ( 31270, -1, 65414, {}, 279 )
	createEntry    ( 31270, -1, 65415, {}, 279 )
	createEntry    ( 31270, -1, 65418, {}, 279 )
	createEntry    ( 31270, -1, 65419, {}, 279 )
	createEntry    ( 31270, -1, 65421, {}, 279 )
	createEntry    ( 31270, -1, 65422, {}, 279 )
	createEntry    ( 31270, -1, 65423, {}, 279 )
	createEntry    ( 31270, -1, 66901, {}, 279 )
	createEntry    ( 31270, -1, 65424, {}, 279 )
	createEntry    ( 31270, -1, 65425, {}, 279 )
	createEntry    ( 31270, -1, 66746, {}, 201 )
	createEntry    ( 31270, -1, 59799, {}, 201 )
	createEntry    ( 31270, -1, 59802, {}, 201 )
	createEntry    ( 31270, -1, 59803, {}, 201 )
	createEntry    ( 31270, -1, 59807, {}, 201 )
	createEntry    ( 31270, -1, 59808, {}, 201 )
	createEntry    ( 31270, -1, 71126, {}, 201 )
	createEntry    ( 31270, -1, 65580, {}, 201 )
	createEntry    ( 31270, -1, 66147, {}, 201 )
	createEntry    ( 31270, -1, 65604, {}, 201 )
	createEntry    ( 31270, -1, 65620, {}, 201 )
	createEntry    ( 31270, -1, 59800, {}, 201 )
	createEntry    ( 31270, -1, 59801, {}, 201 )
	createEntry    ( 31270, -1, 59812, {}, 202 )
	createEntry    ( 31270, -1, 59815, {}, 202 )
	createEntry    ( 31270, -1, 59846, {}, 202 )
	createEntry    ( 31270, -1, 59847, {}, 202 )
	createEntry    ( 31270, -1, 59848, {}, 202 )
	createEntry    ( 31270, -1, 59849, {}, 202 )
	createEntry    ( 31270, -1, 66908, {}, 202 )
	createQuest    ( 31271 )
	createEntry    ( 31271, -1, 27415, {}, nil )
	createEntry    ( 31271, -1, 27416, {}, nil )
	createQuest    ( 31272 )
	createEntry    ( 31272, -1, 27082, {}, nil )
	createEntry    ( 31272, -1, 27083, {}, nil )
	createQuest    ( 31273 )
	createEntry    ( 31273, -1, 26851, {}, nil )
	createEntry    ( 31273, -1, 26852, {}, nil )
	createQuest    ( 31274 )
	createEntry    ( 31274, -1, 27334, {}, nil )
	createEntry    ( 31274, -1, 27335, {}, nil )
	createEntry    ( 31274, -1, 27336, {}, nil )
	createEntry    ( 31274, -1, 27337, {}, nil )
	createEntry    ( 31274, -1, 27338, {}, nil )
	createQuest    ( 31275 )
	createEntry    ( 31275, -1, 26853, {}, nil )
	createEntry    ( 31275, -1, 26854, {}, nil )
	createQuest    ( 31276 )
	createEntry    ( 31276, -1, 26954, {}, nil )
	createEntry    ( 31276, -1, 26955, {}, nil )
	createEntry    ( 31276, -1, 26956, {}, nil )
	createEntry    ( 31276, -1, 26957, {}, nil )
	createQuest    ( 31277 )
	createEntry    ( 31277, -1, 27499, {}, nil )
	createQuest    ( 31278 )
	createEntry    ( 31278, -1, 27062, {}, nil )
	createEntry    ( 31278, -1, 27063, {}, nil )
	createEntry    ( 31278, -1, 27064, {}, nil )
	createQuest    ( 31279 )
	createEntry    ( 31279, -1, 26829, {}, nil )
	createEntry    ( 31279, -1, 27046, {}, nil )
	createEntry    ( 31279, -1, 27047, {}, nil )
	createEntry    ( 31279, -1, 27059, {}, nil )
	createEntry    ( 31279, -1, 27060, {}, nil )
	createEntry    ( 31279, -1, 27172, {}, nil )
	createEntry    ( 31279, -1, 27173, {}, nil )
	createEntry    ( 31279, -1, 27270, {}, nil )
	createEntry    ( 31279, -1, 27455, {}, nil )
	createQuest    ( 31280 )
	createEntry    ( 31280, -1, 27470, {}, nil )
	createQuest    ( 31281 )
	createEntry    ( 31281, -1, 27451, {}, nil )
	createEntry    ( 31281, -1, 27454, {}, nil )
	createEntry    ( 31281, -1, 32158, {}, nil )
	createQuest    ( 31282 )
	createEntry    ( 31282, -1, 27500, {}, nil )
	createQuest    ( 31283 )
	createEntry    ( 31283, -1, 30177, {}, nil )
	createQuest    ( 31284 )
	createEntry    ( 31284, -1, 27079, {}, nil )
	createQuest    ( 31285 )
	createEntry    ( 31285, -1, 27497, {}, nil )
	createQuest    ( 31286 )
	createEntry    ( 31286, -1, 26980, {}, nil )
	createEntry    ( 31286, -1, 26981, {}, nil )
	createEntry    ( 31286, -1, 26983, {}, nil )
	createEntry    ( 31286, -1, 26985, {}, nil )
	createQuest    ( 31287 )
	createEntry    ( 31287, -1, 27106, {}, nil )
	createEntry    ( 31287, -1, 27164, {}, nil )
	createEntry    ( 31287, -1, 27165, {}, nil )
	createQuest    ( 31288 )
	createEntry    ( 31288, -1, 26841, {}, nil )
	createEntry    ( 31288, -1, 26842, {}, nil )
	createEntry    ( 31288, -1, 26843, {}, nil )
	createEntry    ( 31288, -1, 26844, {}, nil )
	createEntry    ( 31288, -1, 26845, {}, nil )
	createEntry    ( 31288, -1, 26846, {}, nil )
	createEntry    ( 31288, -1, 26847, {}, nil )
	createEntry    ( 31288, -1, 27317, {}, nil )
	createEntry    ( 31288, -1, 32175, {}, nil )
	createQuest    ( 31289 )
	createEntry    ( 31289, -1, 26813, {}, nil )
	createEntry    ( 31289, -1, 26814, {}, nil )
	createEntry    ( 31289, -1, 26815, {}, nil )
	createEntry    ( 31289, -1, 27315, {}, nil )
	createEntry    ( 31289, -1, 27413, {}, nil )
	createEntry    ( 31289, -1, 27414, {}, nil )
	createQuest    ( 31290 )
	createEntry    ( 31290, -1, 26816, {}, nil )
	createEntry    ( 31290, -1, 26817, {}, nil )
	createEntry    ( 31290, -1, 26818, {}, nil )
	createEntry    ( 31290, -1, 26819, {}, nil )
	createQuest    ( 31291 )
	createEntry    ( 31291, -1, 26820, {}, nil )
	createEntry    ( 31291, -1, 26821, {}, nil )
	createEntry    ( 31291, -1, 27430, {}, nil )
	createQuest    ( 31292 )
	createEntry    ( 31292, -1, 27360, {}, nil )
	createEntry    ( 31292, -1, 27361, {}, nil )
	createQuest    ( 31293 )
	createEntry    ( 31293, -1, 27450, {}, nil )
	createEntry    ( 31293, -1, 27451, {}, nil )
	createEntry    ( 31293, -1, 27452, {}, nil )
	createEntry    ( 31293, -1, 27453, {}, nil )
	createEntry    ( 31293, -1, 32158, {}, nil )
	createQuest    ( 31294 )
	createEntry    ( 31294, -1, 27076, {}, nil )
	createEntry    ( 31294, -1, 27077, {}, nil )
	createEntry    ( 31294, -1, 27078, {}, nil )
	createEntry    ( 31294, -1, 27125, {}, nil )
	createEntry    ( 31294, -1, 27126, {}, nil )
	createQuest    ( 31295 )
	createEntry    ( 31295, -1, 26848, {}, nil )
	createEntry    ( 31295, -1, 26849, {}, nil )
	createQuest    ( 31296 )
	createEntry    ( 31296, -1, 27320, {}, nil )
	createEntry    ( 31296, -1, 27321, {}, nil )
	createEntry    ( 31296, -1, 27343, {}, nil )
	createQuest    ( 31297 )
	createEntry    ( 31297, -1, 27318, {}, nil )
	createEntry    ( 31297, -1, 27319, {}, nil )
	createEntry    ( 31297, -1, 27322, {}, nil )
	createQuest    ( 31298 )
	createEntry    ( 31298, -1, 27027, {}, nil )
	createEntry    ( 31298, -1, 27028, {}, nil )
	createEntry    ( 31298, -1, 27108, {}, nil )
	createEntry    ( 31298, -1, 27294, {}, nil )
	createQuest    ( 31299 )
	createEntry    ( 31299, -1, 27299, {}, nil )
	createEntry    ( 31299, -1, 27300, {}, nil )
	createQuest    ( 31300 )
	createEntry    ( 31300, -1, 26865, {}, nil )
	createEntry    ( 31300, -1, 26866, {}, nil )
	createEntry    ( 31300, -1, 27090, {}, nil )
	createEntry    ( 31300, -1, 27097, {}, nil )
	createEntry    ( 31300, -1, 27203, {}, nil )
	createEntry    ( 31300, -1, 27204, {}, nil )
	createEntry    ( 31300, -1, 27205, {}, nil )
	createEntry    ( 31300, -1, 27206, {}, nil )
	createQuest    ( 31301 )
	createEntry    ( 31301, -1, 27498, {}, nil )
	createQuest    ( 31302 )
	createEntry    ( 31302, -1, 27305, {}, nil )
	createQuest    ( 31304 )
	createEntry    ( 31304, -1, 26898, {}, nil )
	createEntry    ( 31304, -1, 26902, {}, nil )
	createQuest    ( 31305 )
	createEntry    ( 31305, -1, 26909, {}, nil )
	createQuest    ( 31306 )
	createEntry    ( 31306, -1, 27405, {}, nil )
	createEntry    ( 31306, -1, 27489, {}, nil )
	createEntry    ( 31306, -1, 27490, {}, nil )
	createEntry    ( 31306, -1, 27491, {}, nil )
	createQuest    ( 31307 )
	createEntry    ( 31307, -1, 26919, {}, nil )
	createEntry    ( 31307, -1, 26920, {}, nil )
	createQuest    ( 31308 )
	createEntry    ( 31308, -1, 26928, {}, nil )
	createQuest    ( 31309 )
	createEntry    ( 31309, -1, 26936, {}, nil )
	createEntry    ( 31309, -1, 26937, {}, nil )
	createEntry    ( 31309, -1, 26938, {}, nil )
	createEntry    ( 31309, -1, 26939, {}, nil )
	createEntry    ( 31309, -1, 26944, {}, nil )
	createEntry    ( 31309, -1, 26945, {}, nil )
	createEntry    ( 31309, -1, 26946, {}, nil )
	createQuest    ( 31310 )
	createEntry    ( 31310, -1, 24077, {}, nil )
	createEntry    ( 31310, -1, 26987, {}, nil )
	createEntry    ( 31310, -1, 26988, {}, nil )
	createEntry    ( 31310, -1, 26990, {}, nil )
	createQuest    ( 31311 )
	createEntry    ( 31311, -1, 26992, {}, nil )
	createEntry    ( 31311, -1, 26993, {}, nil )
	createQuest    ( 31312 )
	createEntry    ( 31312, -1, 26994, {}, nil )
	createEntry    ( 31312, -1, 26995, {}, nil )
	createEntry    ( 31312, -1, 26996, {}, nil )
	createEntry    ( 31312, -1, 26997, {}, nil )
	createQuest    ( 31313 )
	createEntry    ( 31313, -1, 27005, {}, nil )
	createEntry    ( 31313, -1, 27006, {}, nil )
	createEntry    ( 31313, -1, 27007, {}, nil )
	createQuest    ( 31314 )
	createEntry    ( 31314, -1, 26959, {}, nil )
	createEntry    ( 31314, -1, 26963, {}, nil )
	createEntry    ( 31314, -1, 26984, {}, nil )
	createEntry    ( 31314, -1, 27137, {}, nil )
	createEntry    ( 31314, -1, 27138, {}, nil )
	createEntry    ( 31314, -1, 27139, {}, nil )
	createEntry    ( 31314, -1, 27140, {}, nil )
	createEntry    ( 31314, -1, 27141, {}, nil )
	createEntry    ( 31314, -1, 27142, {}, nil )
	createEntry    ( 31314, -1, 27143, {}, nil )
	createEntry    ( 31314, -1, 27144, {}, nil )
	createEntry    ( 31314, -1, 27145, {}, nil )
	createEntry    ( 31314, -1, 27146, {}, nil )
	createQuest    ( 31315 )
	createEntry    ( 31315, -1, 26868, {}, nil )
	createEntry    ( 31315, -1, 26914, {}, nil )
	createEntry    ( 31315, -1, 26915, {}, nil )
	createEntry    ( 31315, -1, 26916, {}, nil )
	createEntry    ( 31315, -1, 26917, {}, nil )
	createEntry    ( 31315, -1, 26930, {}, nil )
	createEntry    ( 31315, -1, 27009, {}, nil )
	createEntry    ( 31315, -1, 27011, {}, nil )
	createEntry    ( 31315, -1, 27026, {}, nil )
	createEntry    ( 31315, -1, 27075, {}, nil )
	createEntry    ( 31315, -1, 27166, {}, nil )
	createEntry    ( 31315, -1, 27167, {}, nil )
	createEntry    ( 31315, -1, 27168, {}, nil )
	createEntry    ( 31315, -1, 27169, {}, nil )
	createEntry    ( 31315, -1, 27170, {}, nil )
	createQuest    ( 31316 )
	createEntry    ( 31316, -1, 27012, {}, nil )
	createEntry    ( 31316, -1, 27013, {}, nil )
	createEntry    ( 31316, -1, 27014, {}, nil )
	createEntry    ( 31316, -1, 27015, {}, nil )
	createEntry    ( 31316, -1, 27016, {}, nil )
	createEntry    ( 31316, -1, 27017, {}, nil )
	createEntry    ( 31316, -1, 27018, {}, nil )
	createQuest    ( 31317 )
	createEntry    ( 31317, -1, 27031, {}, nil )
	createEntry    ( 31317, -1, 27032, {}, nil )
	createEntry    ( 31317, -1, 27033, {}, nil )
	createEntry    ( 31317, -1, 27034, {}, nil )
	createEntry    ( 31317, -1, 27521, {}, nil )
	createQuest    ( 31318 )
	createEntry    ( 31318, -1, 27035, {}, nil )
	createEntry    ( 31318, -1, 27036, {}, nil )
	createEntry    ( 31318, -1, 27435, {}, nil )
	createQuest    ( 31319 )
	createEntry    ( 31319, -1, 27193, {}, nil )
	createEntry    ( 31319, -1, 27194, {}, nil )
	createQuest    ( 31320 )
	createEntry    ( 31320, -1, 23521, {}, nil )
	createEntry    ( 31320, -1, 27054, {}, nil )
	createEntry    ( 31320, -1, 27055, {}, nil )
	createQuest    ( 31321 )
	createEntry    ( 31321, -1, 27056, {}, nil )
	createEntry    ( 31321, -1, 27057, {}, nil )
	createEntry    ( 31321, -1, 27058, {}, nil )
	createQuest    ( 31322 )
	createEntry    ( 31322, -1, 27061, {}, nil )
	createQuest    ( 31323 )
	createEntry    ( 31323, -1, 27065, {}, nil )
	createEntry    ( 31323, -1, 27066, {}, nil )
	createEntry    ( 31323, -1, 27068, {}, nil )
	createEntry    ( 31323, -1, 27069, {}, nil )
	createQuest    ( 31324 )
	createEntry    ( 31324, -1, 27070, {}, nil )
	createEntry    ( 31324, -1, 27071, {}, nil )
	createQuest    ( 31325 )
	createEntry    ( 31325, -1, 27074, {}, nil )
	createQuest    ( 31326 )
	createEntry    ( 31326, -1, 27114, {}, nil )
	createQuest    ( 31327 )
	createEntry    ( 31327, -1, 21268, {}, nil )
	createEntry    ( 31327, -1, 26929, {}, nil )
	createEntry    ( 31327, -1, 27172, {}, nil )
	createEntry    ( 31327, -1, 27267, {}, nil )
	createEntry    ( 31327, -1, 27268, {}, nil )
	createEntry    ( 31327, -1, 27269, {}, nil )
	createEntry    ( 31327, -1, 27270, {}, nil )
	createEntry    ( 31327, -1, 27436, {}, nil )
	createEntry    ( 31327, -1, 31453, {}, nil )
	createQuest    ( 31328 )
	createEntry    ( 31328, -1, 26947, {}, nil )
	createEntry    ( 31328, -1, 26948, {}, nil )
	createEntry    ( 31328, -1, 26949, {}, nil )
	createEntry    ( 31328, -1, 26950, {}, nil )
	createQuest    ( 31329 )
	createEntry    ( 31329, -1, 27019, {}, nil )
	createEntry    ( 31329, -1, 27020, {}, nil )
	createEntry    ( 31329, -1, 27021, {}, nil )
	createEntry    ( 31329, -1, 27022, {}, nil )
	createQuest    ( 31330 )
	createEntry    ( 31330, -1, 27121, {}, nil )
	createEntry    ( 31330, -1, 27122, {}, nil )
	createQuest    ( 31331 )
	createEntry    ( 31331, -1, 27113, {}, nil )
	createQuest    ( 31332 )
	createEntry    ( 31332, -1, 27112, {}, nil )
	createQuest    ( 31333 )
	createEntry    ( 31333, -1, 27120, {}, nil )
	createQuest    ( 31334 )
	createEntry    ( 31334, -1, 27130, {}, nil )
	createQuest    ( 31335 )
	createEntry    ( 31335, -1, 27128, {}, nil )
	createEntry    ( 31335, -1, 27129, {}, nil )
	createEntry    ( 31335, -1, 27130, {}, nil )
	createQuest    ( 31336 )
	createEntry    ( 31336, -1, 27213, {}, nil )
	createEntry    ( 31336, -1, 27216, {}, nil )
	createQuest    ( 31337 )
	createEntry    ( 31337, -1, 27067, {}, nil )
	createQuest    ( 31338 )
	createEntry    ( 31338, -1, 27475, {}, nil )
	createQuest    ( 31339 )
	createEntry    ( 31339, -1, 27133, {}, nil )
	createEntry    ( 31339, -1, 27134, {}, nil )
	createEntry    ( 31339, -1, 27135, {}, nil )
	createQuest    ( 31340 )
	createEntry    ( 31340, -1, 26883, {}, nil )
	createEntry    ( 31340, -1, 26884, {}, nil )
	createQuest    ( 31341 )
	createEntry    ( 31341, -1, 27153, {}, nil )
	createQuest    ( 31342 )
	createEntry    ( 31342, -1, 26927, {}, nil )
	createEntry    ( 31342, -1, 26958, {}, nil )
	createEntry    ( 31342, -1, 26965, {}, nil )
	createEntry    ( 31342, -1, 26991, {}, nil )
	createEntry    ( 31342, -1, 27045, {}, nil )
	createEntry    ( 31342, -1, 27136, {}, nil )
	createEntry    ( 31342, -1, 27147, {}, nil )
	createEntry    ( 31342, -1, 27157, {}, nil )
	createEntry    ( 31342, -1, 27158, {}, nil )
	createEntry    ( 31342, -1, 27159, {}, nil )
	createEntry    ( 31342, -1, 27160, {}, nil )
	createEntry    ( 31342, -1, 27161, {}, nil )
	createEntry    ( 31342, -1, 27174, {}, nil )
	createEntry    ( 31342, -1, 27175, {}, nil )
	createEntry    ( 31342, -1, 27176, {}, nil )
	createEntry    ( 31342, -1, 27328, {}, nil )
	createEntry    ( 31342, -1, 27389, {}, nil )
	createEntry    ( 31342, -1, 27393, {}, nil )
	createEntry    ( 31342, -1, 27479, {}, nil )
	createEntry    ( 31342, -1, 27494, {}, nil )
	createQuest    ( 31343 )
	createEntry    ( 31343, -1, 26822, {}, nil )
	createEntry    ( 31343, -1, 26823, {}, nil )
	createEntry    ( 31343, -1, 26824, {}, nil )
	createEntry    ( 31343, -1, 26825, {}, nil )
	createEntry    ( 31343, -1, 26826, {}, nil )
	createEntry    ( 31343, -1, 26827, {}, nil )
	createEntry    ( 31343, -1, 26828, {}, nil )
	createQuest    ( 31344 )
	createEntry    ( 31344, -1, 26839, {}, nil )
	createEntry    ( 31344, -1, 26840, {}, nil )
	createEntry    ( 31344, -1, 26885, {}, nil )
	createEntry    ( 31344, -1, 26886, {}, nil )
	createEntry    ( 31344, -1, 26921, {}, nil )
	createEntry    ( 31344, -1, 26922, {}, nil )
	createEntry    ( 31344, -1, 26978, {}, nil )
	createEntry    ( 31344, -1, 27041, {}, nil )
	createEntry    ( 31344, -1, 27042, {}, nil )
	createEntry    ( 31344, -1, 27043, {}, nil )
	createEntry    ( 31344, -1, 27044, {}, nil )
	createEntry    ( 31344, -1, 27224, {}, nil )
	createEntry    ( 31344, -1, 27271, {}, nil )
	createEntry    ( 31344, -1, 27272, {}, nil )
	createEntry    ( 31344, -1, 27273, {}, nil )
	createEntry    ( 31344, -1, 27296, {}, nil )
	createQuest    ( 31345 )
	createEntry    ( 31345, -1, 27182, {}, nil )
	createQuest    ( 31346 )
	createEntry    ( 31346, -1, 27184, {}, nil )
	createEntry    ( 31346, -1, 27185, {}, nil )
	createQuest    ( 31347 )
	createEntry    ( 31347, -1, 27188, {}, nil )
	createEntry    ( 31347, -1, 27189, {}, nil )
	createQuest    ( 31348 )
	createEntry    ( 31348, -1, 27221, {}, nil )
	createEntry    ( 31348, -1, 27222, {}, nil )
	createQuest    ( 31349 )
	createEntry    ( 31349, -1, 27101, {}, nil )
	createEntry    ( 31349, -1, 27102, {}, nil )
	createQuest    ( 31350 )
	createEntry    ( 31350, -1, 27194, {}, nil )
	createQuest    ( 31351 )
	createEntry    ( 31351, -1, 27202, {}, nil )
	createQuest    ( 31352 )
	createEntry    ( 31352, -1, 27127, {}, nil )
	createEntry    ( 31352, -1, 27225, {}, nil )
	createEntry    ( 31352, -1, 27226, {}, nil )
	createEntry    ( 31352, -1, 27227, {}, nil )
	createQuest    ( 31353 )
	createEntry    ( 31353, -1, 27235, {}, nil )
	createQuest    ( 31354 )
	createEntry    ( 31354, -1, 27236, {}, nil )
	createQuest    ( 31355 )
	createEntry    ( 31355, -1, 27231, {}, nil )
	createEntry    ( 31355, -1, 27232, {}, nil )
	createEntry    ( 31355, -1, 27233, {}, nil )
	createQuest    ( 31356 )
	createEntry    ( 31356, -1, 27234, {}, nil )
	createQuest    ( 31357 )
	createEntry    ( 31357, -1, 26893, {}, nil )
	createEntry    ( 31357, -1, 26894, {}, nil )
	createEntry    ( 31357, -1, 26895, {}, nil )
	createEntry    ( 31357, -1, 26896, {}, nil )
	createQuest    ( 31358 )
	createEntry    ( 31358, -1, 27211, {}, nil )
	createQuest    ( 31359 )
	createEntry    ( 31359, -1, 27249, {}, nil )
	createEntry    ( 31359, -1, 27250, {}, nil )
	createEntry    ( 31359, -1, 27251, {}, nil )
	createQuest    ( 31360 )
	createEntry    ( 31360, -1, 26793, {}, nil )
	createEntry    ( 31360, -1, 26982, {}, nil )
	createEntry    ( 31360, -1, 27183, {}, nil )
	createEntry    ( 31360, -1, 27240, {}, nil )
	createEntry    ( 31360, -1, 27241, {}, nil )
	createEntry    ( 31360, -1, 27242, {}, nil )
	createEntry    ( 31360, -1, 27243, {}, nil )
	createEntry    ( 31360, -1, 27253, {}, nil )
	createEntry    ( 31360, -1, 31188, {}, nil )
	createQuest    ( 31361 )
	createEntry    ( 31361, -1, 27258, {}, nil )
	createQuest    ( 31362 )
	createEntry    ( 31362, -1, 27256, {}, nil )
	createEntry    ( 31362, -1, 27257, {}, nil )
	createQuest    ( 31363 )
	createEntry    ( 31363, -1, 27477, {}, nil )
	createEntry    ( 31363, -1, 27478, {}, nil )
	createQuest    ( 31364 )
	createEntry    ( 31364, -1, 27276, {}, nil )
	createEntry    ( 31364, -1, 27278, {}, nil )
	createQuest    ( 31365 )
	createEntry    ( 31365, -1, 27277, {}, nil )
	createQuest    ( 31366 )
	createEntry    ( 31366, -1, 27428, {}, nil )
	createEntry    ( 31366, -1, 27429, {}, nil )
	createQuest    ( 31367 )
	createEntry    ( 31367, -1, 27084, {}, nil )
	createQuest    ( 31368 )
	createEntry    ( 31368, -1, 27051, {}, nil )
	createEntry    ( 31368, -1, 27301, {}, nil )
	createEntry    ( 31368, -1, 27302, {}, nil )
	createQuest    ( 31369 )
	createEntry    ( 31369, -1, 27307, {}, nil )
	createEntry    ( 31369, -1, 27308, {}, nil )
	createEntry    ( 31369, -1, 27309, {}, nil )
	createEntry    ( 31369, -1, 27310, {}, nil )
	createEntry    ( 31369, -1, 27311, {}, nil )
	createEntry    ( 31369, -1, 27312, {}, nil )
	createEntry    ( 31369, -1, 27313, {}, nil )
	createEntry    ( 31369, -1, 27314, {}, nil )
	createEntry    ( 31369, -1, 27316, {}, nil )
	createQuest    ( 31370 )
	createEntry    ( 31370, -1, 27323, {}, nil )
	createEntry    ( 31370, -1, 27324, {}, nil )
	createQuest    ( 31371 )
	createEntry    ( 31371, -1, 27341, {}, nil )
	createEntry    ( 31371, -1, 27342, {}, nil )
	createQuest    ( 31372 )
	createEntry    ( 31372, -1, 26913, {}, nil )
	createQuest    ( 31373 )
	createEntry    ( 31373, -1, 27419, {}, nil )
	createEntry    ( 31373, -1, 27420, {}, nil )
	createQuest    ( 31374 )
	createEntry    ( 31374, -1, 26925, {}, nil )
	createQuest    ( 31375 )
	createEntry    ( 31375, -1, 27344, {}, nil )
	createEntry    ( 31375, -1, 27345, {}, nil )
	createQuest    ( 31376 )
	createEntry    ( 31376, -1, 27349, {}, nil )
	createEntry    ( 31376, -1, 27350, {}, nil )
	createQuest    ( 31377 )
	createEntry    ( 31377, -1, 27347, {}, nil )
	createQuest    ( 31378 )
	createEntry    ( 31378, -1, 27354, {}, nil )
	createEntry    ( 31378, -1, 27355, {}, nil )
	createEntry    ( 31378, -1, 27356, {}, nil )
	createQuest    ( 31379 )
	createEntry    ( 31379, -1, 26879, {}, nil )
	createEntry    ( 31379, -1, 26880, {}, nil )
	createEntry    ( 31379, -1, 26881, {}, nil )
	createEntry    ( 31379, -1, 26882, {}, nil )
	createEntry    ( 31379, -1, 27358, {}, nil )
	createQuest    ( 31380 )
	createEntry    ( 31380, -1, 26870, {}, nil )
	createQuest    ( 31381 )
	createEntry    ( 31381, -1, 27362, {}, nil )
	createEntry    ( 31381, -1, 27363, {}, nil )
	createEntry    ( 31381, -1, 27364, {}, nil )
	createQuest    ( 31382 )
	createEntry    ( 31382, -1, 27214, {}, nil )
	createEntry    ( 31382, -1, 27215, {}, nil )
	createQuest    ( 31383 )
	createEntry    ( 31383, -1, 27104, {}, nil )
	createEntry    ( 31383, -1, 27346, {}, nil )
	createEntry    ( 31383, -1, 27348, {}, nil )
	createEntry    ( 31383, -1, 27367, {}, nil )
	createEntry    ( 31383, -1, 27368, {}, nil )
	createEntry    ( 31383, -1, 27369, {}, nil )
	createEntry    ( 31383, -1, 27372, {}, nil )
	createQuest    ( 31384 )
	createEntry    ( 31384, -1, 27171, {}, nil )
	createQuest    ( 31385 )
	createEntry    ( 31385, -1, 27376, {}, nil )
	createEntry    ( 31385, -1, 27377, {}, nil )
	createQuest    ( 31386 )
	createEntry    ( 31386, -1, 26923, {}, nil )
	createEntry    ( 31386, -1, 26924, {}, nil )
	createEntry    ( 31386, -1, 27154, {}, nil )
	createEntry    ( 31386, -1, 27155, {}, nil )
	createEntry    ( 31386, -1, 27156, {}, nil )
	createQuest    ( 31387 )
	createEntry    ( 31387, -1, 27411, {}, nil )
	createEntry    ( 31387, -1, 27412, {}, nil )
	createQuest    ( 31388 )
	createEntry    ( 31388, -1, 27029, {}, nil )
	createEntry    ( 31388, -1, 27030, {}, nil )
	createEntry    ( 31388, -1, 27274, {}, nil )
	createEntry    ( 31388, -1, 27275, {}, nil )
	createQuest    ( 31389 )
	createEntry    ( 31389, -1, 26873, {}, nil )
	createEntry    ( 31389, -1, 26874, {}, nil )
	createEntry    ( 31389, -1, 26903, {}, nil )
	createEntry    ( 31389, -1, 26910, {}, nil )
	createEntry    ( 31389, -1, 26911, {}, nil )
	createEntry    ( 31389, -1, 26969, {}, nil )
	createEntry    ( 31389, -1, 26970, {}, nil )
	createEntry    ( 31389, -1, 26971, {}, nil )
	createEntry    ( 31389, -1, 26972, {}, nil )
	createEntry    ( 31389, -1, 26973, {}, nil )
	createEntry    ( 31389, -1, 26974, {}, nil )
	createEntry    ( 31389, -1, 26975, {}, nil )
	createEntry    ( 31389, -1, 26976, {}, nil )
	createEntry    ( 31389, -1, 26977, {}, nil )
	createQuest    ( 31390 )
	createEntry    ( 31390, -1, 26811, {}, nil )
	createEntry    ( 31390, -1, 27092, {}, nil )
	createEntry    ( 31390, -1, 27148, {}, nil )
	createEntry    ( 31390, -1, 27187, {}, nil )
	createEntry    ( 31390, -1, 27219, {}, nil )
	createEntry    ( 31390, -1, 27220, {}, nil )
	createEntry    ( 31390, -1, 27282, {}, nil )
	createEntry    ( 31390, -1, 27290, {}, nil )
	createEntry    ( 31390, -1, 27386, {}, nil )
	createEntry    ( 31390, -1, 27388, {}, nil )
	createEntry    ( 31390, -1, 27390, {}, nil )
	createEntry    ( 31390, -1, 27391, {}, nil )
	createEntry    ( 31390, -1, 27392, {}, nil )
	createEntry    ( 31390, -1, 27394, {}, nil )
	createEntry    ( 31390, -1, 27408, {}, nil )
	createEntry    ( 31390, -1, 27409, {}, nil )
	createQuest    ( 31391 )
	createEntry    ( 31391, -1, 27086, {}, nil )
	createEntry    ( 31391, -1, 27123, {}, nil )
	createEntry    ( 31391, -1, 27124, {}, nil )
	createQuest    ( 31392 )
	createEntry    ( 31392, -1, 27421, {}, nil )
	createQuest    ( 31393 )
	createEntry    ( 31393, -1, 27424, {}, nil )
	createQuest    ( 31394 )
	createEntry    ( 31394, -1, 27177, {}, nil )
	createEntry    ( 31394, -1, 27178, {}, nil )
	createEntry    ( 31394, -1, 27179, {}, nil )
	createQuest    ( 31395 )
	createEntry    ( 31395, -1, 27247, {}, nil )
	createEntry    ( 31395, -1, 27248, {}, nil )
	createQuest    ( 31396 )
	createEntry    ( 31396, -1, 26960, {}, nil )
	createEntry    ( 31396, -1, 27162, {}, nil )
	createEntry    ( 31396, -1, 27163, {}, nil )
	createQuest    ( 31397 )
	createEntry    ( 31397, -1, 27486, {}, nil )
	createEntry    ( 31397, -1, 27487, {}, nil )
	createQuest    ( 31398 )
	createEntry    ( 31398, -1, 27458, {}, nil )
	createEntry    ( 31398, -1, 27459, {}, nil )
	createEntry    ( 31398, -1, 27460, {}, nil )
	createQuest    ( 31399 )
	createEntry    ( 31399, -1, 27461, {}, nil )
	createEntry    ( 31399, -1, 27462, {}, nil )
	createEntry    ( 31399, -1, 27463, {}, nil )
	createEntry    ( 31399, -1, 27464, {}, nil )
	createEntry    ( 31399, -1, 27465, {}, nil )
	createEntry    ( 31399, -1, 27466, {}, nil )
	createQuest    ( 31400 )
	createEntry    ( 31400, -1, 20597, {}, nil )
	createEntry    ( 31400, -1, 26858, {}, nil )
	createEntry    ( 31400, -1, 26872, {}, nil )
	createEntry    ( 31400, -1, 27505, {}, nil )
	createEntry    ( 31400, -1, 27513, {}, nil )
	createQuest    ( 31401 )
	createEntry    ( 31401, -1, 26850, {}, nil )
	createEntry    ( 31401, -1, 26856, {}, nil )
	createEntry    ( 31401, -1, 26857, {}, nil )
	createEntry    ( 31401, -1, 26859, {}, nil )
	createEntry    ( 31401, -1, 26860, {}, nil )
	createEntry    ( 31401, -1, 26861, {}, nil )
	createEntry    ( 31401, -1, 26862, {}, nil )
	createEntry    ( 31401, -1, 27217, {}, nil )
	createEntry    ( 31401, -1, 27218, {}, nil )
	createEntry    ( 31401, -1, 27378, {}, nil )
	createEntry    ( 31401, -1, 27379, {}, nil )
	createEntry    ( 31401, -1, 27380, {}, nil )
	createEntry    ( 31401, -1, 27381, {}, nil )
	createEntry    ( 31401, -1, 27382, {}, nil )
	createEntry    ( 31401, -1, 27383, {}, nil )
	createEntry    ( 31401, -1, 27468, {}, nil )
	createEntry    ( 31401, -1, 27469, {}, nil )
	createEntry    ( 31401, -1, 27473, {}, nil )
	createEntry    ( 31401, -1, 27474, {}, nil )
	createEntry    ( 31401, -1, 27476, {}, nil )
	createEntry    ( 31401, -1, 27492, {}, nil )
	createQuest    ( 31402 )
	createEntry    ( 31402, -1, 27374, {}, nil )
	createEntry    ( 31402, -1, 27375, {}, nil )
	createQuest    ( 31403 )
	createEntry    ( 31403, -1, 27115, {}, nil )
	createEntry    ( 31403, -1, 27116, {}, nil )
	createEntry    ( 31403, -1, 27117, {}, nil )
	createEntry    ( 31403, -1, 27118, {}, nil )
	createEntry    ( 31403, -1, 27119, {}, nil )
	createQuest    ( 31404 )
	createEntry    ( 31404, -1, 27431, {}, nil )
	createEntry    ( 31404, -1, 27432, {}, nil )
	createQuest    ( 31405 )
	createEntry    ( 31405, -1, 26931, {}, nil )
	createEntry    ( 31405, -1, 26932, {}, nil )
	createEntry    ( 31405, -1, 26933, {}, nil )
	createEntry    ( 31405, -1, 26934, {}, nil )
	createQuest    ( 31406 )
	createEntry    ( 31406, -1, 27517, {}, nil )
	createQuest    ( 31407 )
	createEntry    ( 31407, -1, 27288, {}, nil )
	createQuest    ( 31408 )
	createEntry    ( 31408, -1, 26986, {}, nil )
	createEntry    ( 31408, -1, 27008, {}, nil )
	createEntry    ( 31408, -1, 27186, {}, nil )
	createEntry    ( 31408, -1, 27397, {}, nil )
	createEntry    ( 31408, -1, 27422, {}, nil )
	createEntry    ( 31408, -1, 27423, {}, nil )
	createEntry    ( 31408, -1, 27425, {}, nil )
	createEntry    ( 31408, -1, 27426, {}, nil )
	createEntry    ( 31408, -1, 27427, {}, nil )
	createQuest    ( 31409 )
	createEntry    ( 31409, -1, 8058, {}, nil )
	createEntry    ( 31409, -1, 27279, {}, nil )
	createQuest    ( 31410 )
	createEntry    ( 31410, -1, 26806, {}, nil )
	createEntry    ( 31410, -1, 26807, {}, nil )
	createEntry    ( 31410, -1, 26808, {}, nil )
	createEntry    ( 31410, -1, 26809, {}, nil )
	createEntry    ( 31410, -1, 26810, {}, nil )
	createEntry    ( 31410, -1, 27384, {}, nil )
	createEntry    ( 31410, -1, 27385, {}, nil )
	createQuest    ( 31411 )
	createEntry    ( 31411, -1, 27439, {}, nil )
	createEntry    ( 31411, -1, 27440, {}, nil )
	createEntry    ( 31411, -1, 27441, {}, nil )
	createEntry    ( 31411, -1, 27442, {}, nil )
	createEntry    ( 31411, -1, 27443, {}, nil )
	createEntry    ( 31411, -1, 27444, {}, nil )
	createEntry    ( 31411, -1, 27445, {}, nil )
	createEntry    ( 31411, -1, 27446, {}, nil )
	createEntry    ( 31411, -1, 27447, {}, nil )
	createEntry    ( 31411, -1, 27448, {}, nil )
	createEntry    ( 31411, -1, 27471, {}, nil )
	createEntry    ( 31411, -1, 27472, {}, nil )
	createQuest    ( 31412 )
	createEntry    ( 31412, -1, 26855, {}, nil )
	createEntry    ( 31412, -1, 27073, {}, nil )
	createEntry    ( 31412, -1, 27244, {}, nil )
	createEntry    ( 31412, -1, 27245, {}, nil )
	createEntry    ( 31412, -1, 27246, {}, nil )
	createQuest    ( 31413 )
	createEntry    ( 31413, -1, 27237, {}, nil )
	createEntry    ( 31413, -1, 27238, {}, nil )
	createEntry    ( 31413, -1, 27239, {}, nil )
	createQuest    ( 31414 )
	createEntry    ( 31414, -1, 26935, {}, nil )
	createEntry    ( 31414, -1, 26940, {}, nil )
	createEntry    ( 31414, -1, 26941, {}, nil )
	createEntry    ( 31414, -1, 26942, {}, nil )
	createEntry    ( 31414, -1, 26943, {}, nil )
	createEntry    ( 31414, -1, 26951, {}, nil )
	createEntry    ( 31414, -1, 26952, {}, nil )
	createEntry    ( 31414, -1, 26953, {}, nil )
	createEntry    ( 31414, -1, 27023, {}, nil )
	createEntry    ( 31414, -1, 27024, {}, nil )
	createEntry    ( 31414, -1, 27025, {}, nil )
	createEntry    ( 31414, -1, 27052, {}, nil )
	createEntry    ( 31414, -1, 27053, {}, nil )
	createEntry    ( 31414, -1, 27072, {}, nil )
	createEntry    ( 31414, -1, 27191, {}, nil )
	createEntry    ( 31414, -1, 27195, {}, nil )
	createEntry    ( 31414, -1, 27196, {}, nil )
	createEntry    ( 31414, -1, 27197, {}, nil )
	createEntry    ( 31414, -1, 27198, {}, nil )
	createEntry    ( 31414, -1, 27199, {}, nil )
	createEntry    ( 31414, -1, 27200, {}, nil )
	createEntry    ( 31414, -1, 27228, {}, nil )
	createEntry    ( 31414, -1, 27229, {}, nil )
	createEntry    ( 31414, -1, 27230, {}, nil )
	createEntry    ( 31414, -1, 27252, {}, nil )
	createEntry    ( 31414, -1, 27265, {}, nil )
	createEntry    ( 31414, -1, 27266, {}, nil )
	createEntry    ( 31414, -1, 27438, {}, nil )
	createEntry    ( 31414, -1, 27456, {}, nil )
	createEntry    ( 31414, -1, 27457, {}, nil )
	createQuest    ( 31415 )
	createEntry    ( 31415, -1, 26908, {}, nil )
	createEntry    ( 31415, -1, 27107, {}, nil )
	createEntry    ( 31415, -1, 27259, {}, nil )
	createEntry    ( 31415, -1, 27260, {}, nil )
	createEntry    ( 31415, -1, 27261, {}, nil )
	createEntry    ( 31415, -1, 27262, {}, nil )
	createEntry    ( 31415, -1, 27263, {}, nil )
	createEntry    ( 31415, -1, 27293, {}, nil )
	createEntry    ( 31415, -1, 27295, {}, nil )
	createQuest    ( 31416 )
	createEntry    ( 31416, -1, 26812, {}, nil )
	createEntry    ( 31416, -1, 26871, {}, nil )
	createEntry    ( 31416, -1, 26892, {}, nil )
	createEntry    ( 31416, -1, 26962, {}, nil )
	createEntry    ( 31416, -1, 26967, {}, nil )
	createEntry    ( 31416, -1, 27091, {}, nil )
	createEntry    ( 31416, -1, 27093, {}, nil )
	createEntry    ( 31416, -1, 27094, {}, nil )
	createEntry    ( 31416, -1, 27095, {}, nil )
	createEntry    ( 31416, -1, 27096, {}, nil )
	createEntry    ( 31416, -1, 27132, {}, nil )
	createEntry    ( 31416, -1, 27190, {}, nil )
	createEntry    ( 31416, -1, 27192, {}, nil )
	createEntry    ( 31416, -1, 27201, {}, nil )
	createEntry    ( 31416, -1, 27283, {}, nil )
	createEntry    ( 31416, -1, 27284, {}, nil )
	createEntry    ( 31416, -1, 27285, {}, nil )
	createEntry    ( 31416, -1, 27286, {}, nil )
	createEntry    ( 31416, -1, 27287, {}, nil )
	createEntry    ( 31416, -1, 27327, {}, nil )
	createEntry    ( 31416, -1, 27329, {}, nil )
	createEntry    ( 31416, -1, 27330, {}, nil )
	createEntry    ( 31416, -1, 27331, {}, nil )
	createEntry    ( 31416, -1, 27332, {}, nil )
	createEntry    ( 31416, -1, 27333, {}, nil )
	createEntry    ( 31416, -1, 27339, {}, nil )
	createEntry    ( 31416, -1, 27340, {}, nil )
	createEntry    ( 31416, -1, 27352, {}, nil )
	createEntry    ( 31416, -1, 27387, {}, nil )
	createEntry    ( 31416, -1, 27399, {}, nil )
	createEntry    ( 31416, -1, 27488, {}, nil )
	createEntry    ( 31416, -1, 27514, {}, nil )
	createQuest    ( 31417 )
	createEntry    ( 31417, -1, 26966, {}, nil )
	createEntry    ( 31417, -1, 27207, {}, nil )
	createEntry    ( 31417, -1, 27208, {}, nil )
	createEntry    ( 31417, -1, 27209, {}, nil )
	createEntry    ( 31417, -1, 27210, {}, nil )
	createQuest    ( 31418 )
	createEntry    ( 31418, -1, 26830, {}, nil )
	createEntry    ( 31418, -1, 26831, {}, nil )
	createEntry    ( 31418, -1, 26832, {}, nil )
	createEntry    ( 31418, -1, 26833, {}, nil )
	createEntry    ( 31418, -1, 26834, {}, nil )
	createEntry    ( 31418, -1, 26838, {}, nil )
	createEntry    ( 31418, -1, 26887, {}, nil )
	createEntry    ( 31418, -1, 26888, {}, nil )
	createEntry    ( 31418, -1, 27105, {}, nil )
	createEntry    ( 31418, -1, 27292, {}, nil )
	createEntry    ( 31418, -1, 27303, {}, nil )
	createEntry    ( 31418, -1, 27304, {}, nil )
	createEntry    ( 31418, -1, 27507, {}, nil )
	createQuest    ( 31419 )
	createEntry    ( 31419, -1, 23508, {}, nil )
	createEntry    ( 31419, -1, 26867, {}, nil )
	createEntry    ( 31419, -1, 27481, {}, nil )
	createEntry    ( 31419, -1, 27483, {}, nil )
	createEntry    ( 31419, -1, 27484, {}, nil )
	createQuest    ( 31420 )
	createEntry    ( 31420, -1, 27495, {}, nil )
	createQuest    ( 31421 )
	createEntry    ( 31421, -1, 1827, {}, nil )
	createEntry    ( 31421, -1, 6332, {}, nil )
	createEntry    ( 31421, -1, 6354, {}, nil )
	createEntry    ( 31421, -1, 6355, {}, nil )
	createEntry    ( 31421, -1, 6356, {}, nil )
	createEntry    ( 31421, -1, 27493, {}, nil )
	createEntry    ( 31421, -1, 27503, {}, nil )
	createEntry    ( 31421, -1, 27504, {}, nil )
	createQuest    ( 31422 )
	createEntry    ( 31422, -1, 5815, {}, nil )
	createEntry    ( 31422, -1, 5816, {}, nil )
	createEntry    ( 31422, -1, 26835, {}, nil )
	createEntry    ( 31422, -1, 26836, {}, nil )
	createEntry    ( 31422, -1, 26863, {}, nil )
	createEntry    ( 31422, -1, 26864, {}, nil )
	createEntry    ( 31422, -1, 26869, {}, nil )
	createEntry    ( 31422, -1, 26875, {}, nil )
	createEntry    ( 31422, -1, 26876, {}, nil )
	createEntry    ( 31422, -1, 26877, {}, nil )
	createEntry    ( 31422, -1, 26878, {}, nil )
	createEntry    ( 31422, -1, 26912, {}, nil )
	createEntry    ( 31422, -1, 26999, {}, nil )
	createEntry    ( 31422, -1, 27000, {}, nil )
	createEntry    ( 31422, -1, 27001, {}, nil )
	createEntry    ( 31422, -1, 27098, {}, nil )
	createEntry    ( 31422, -1, 27099, {}, nil )
	createEntry    ( 31422, -1, 27100, {}, nil )
	createEntry    ( 31422, -1, 27103, {}, nil )
	createEntry    ( 31422, -1, 27264, {}, nil )
	createEntry    ( 31422, -1, 27280, {}, nil )
	createEntry    ( 31422, -1, 27281, {}, nil )
	createEntry    ( 31422, -1, 27289, {}, nil )
	createEntry    ( 31422, -1, 27291, {}, nil )
	createEntry    ( 31422, -1, 27297, {}, nil )
	createEntry    ( 31422, -1, 27298, {}, nil )
	createEntry    ( 31422, -1, 27395, {}, nil )
	createEntry    ( 31422, -1, 27396, {}, nil )
	createEntry    ( 31422, -1, 27400, {}, nil )
	createEntry    ( 31422, -1, 27401, {}, nil )
	createEntry    ( 31422, -1, 27402, {}, nil )
	createEntry    ( 31422, -1, 27403, {}, nil )
	createEntry    ( 31422, -1, 27404, {}, nil )
	createEntry    ( 31422, -1, 27407, {}, nil )
	createEntry    ( 31422, -1, 27410, {}, nil )
	createEntry    ( 31422, -1, 27417, {}, nil )
	createEntry    ( 31422, -1, 27506, {}, nil )
	createQuest    ( 31423 )
	createEntry    ( 31423, -1, 30178, {}, nil )
	createEntry    ( 31423, -1, 30179, {}, nil )
	createEntry    ( 31423, -1, 31698, {}, nil )
	createQuest    ( 31424 )
	createEntry    ( 31424, -1, 27496, {}, nil )
	createQuest    ( 31425 )
	createEntry    ( 31425, -1, 27501, {}, nil )
	createEntry    ( 31425, -1, 27502, {}, nil )
	createQuest    ( 31426 )
	createEntry    ( 31426, -1, 27433, {}, nil )
	createQuest    ( 31427 )
	createEntry    ( 31427, -1, 27515, {}, nil )
	createEntry    ( 31427, -1, 27516, {}, nil )
	createQuest    ( 31428 )
	createEntry    ( 31428, -1, 27152, {}, nil )
	createQuest    ( 31429 )
	createEntry    ( 31429, -1, 27518, {}, nil )
	createQuest    ( 31430 )
	createEntry    ( 31430, -1, 27519, {}, nil )
	createEntry    ( 31430, -1, 27520, {}, nil )
	createQuest    ( 31431 )
	createEntry    ( 31431, -1, 27511, {}, nil )
	createEntry    ( 31431, -1, 27512, {}, nil )
	createQuest    ( 31604 )
	createEntry    ( 31604, -1, 27149, {}, nil )
	createEntry    ( 31604, -1, 27150, {}, nil )
	createEntry    ( 31604, -1, 27151, {}, nil )
	createQuest    ( 31605 )
	createEntry    ( 31605, -1, 27109, {}, nil )
	createEntry    ( 31605, -1, 27110, {}, nil )
	createEntry    ( 31605, -1, 27111, {}, nil )
	createQuest    ( 31606 )
	createEntry    ( 31606, -1, 27080, {}, nil )
	createEntry    ( 31606, -1, 27081, {}, nil )
	createQuest    ( 31607 )
	createEntry    ( 31607, -1, 27085, {}, nil )
	createEntry    ( 31607, -1, 27087, {}, nil )
	createQuest    ( 31092 )
	createEntry    ( 31092, -1, 28403, {}, nil )
	createEntry    ( 31092, -1, 28427, {}, nil )
	createEntry    ( 31092, -1, 28433, {}, nil )
	createEntry    ( 31092, -1, 28458, {}, nil )
	createEntry    ( 31092, -1, 28479, {}, nil )
	createEntry    ( 31092, -1, 28503, {}, nil )
	createEntry    ( 31092, -1, 28521, {}, nil )
	createEntry    ( 31092, -1, 28536, {}, nil )
	createEntry    ( 31092, -1, 30814, {}, nil )
	createEntry    ( 31092, -1, 30815, {}, nil )
	createEntry    ( 31092, -1, 30816, {}, nil )
	createEntry    ( 31092, -1, 30817, {}, nil )
	createEntry    ( 31092, -1, 30818, {}, nil )
	createQuest    ( 28607 )
	createEntry    ( 28607, -1, 29022, {}, nil )
	createEntry    ( 28607, -1, 29023, {}, nil )
	createEntry    ( 28607, -1, 30771, {}, nil )
	createEntry    ( 28607, -1, 30772, {}, nil )
	createEntry    ( 28607, -1, 30773, {}, nil )
	createEntry    ( 28607, -1, 30774, {}, nil )
	createEntry    ( 28607, -1, 30775, {}, nil )
	createEntry    ( 28607, -1, 30776, {}, nil )
	createEntry    ( 28607, -1, 30777, {}, nil )
	createEntry    ( 28607, -1, 30778, {}, nil )
	createQuest    ( 27633 )
	createEntry    ( 27633, -1, 31608, {}, nil )
	createEntry    ( 27633, -1, 31609, {}, nil )
	createEntry    ( 27633, -1, 31610, {}, nil )
	createEntry    ( 27633, -1, 31611, {}, nil )
	createEntry    ( 27633, -1, 31612, {}, nil )
	createEntry    ( 27633, -1, 31613, {}, nil )
	createEntry    ( 27633, -1, 31614, {}, nil )
	createEntry    ( 27633, -1, 31615, {}, nil )
	createEntry    ( 27633, -1, 31616, {}, nil )
	createEntry    ( 27633, -1, 31617, {}, nil )
	createEntry    ( 27633, -1, 31618, {}, nil )
	createQuest    ( 18675 )
	createEntry    ( 18675, -1, 26979, {}, nil )
	createEntry    ( 18675, -1, 27223, {}, nil )
	createQuest    ( 31988 )
	createEntry    ( 31988, -1, 26918, {}, nil )
	createEntry    ( 31988, -1, 31969, {}, nil )
	createQuest    ( 32148 )
	createEntry    ( 32148, -1, 27212, {}, nil )
	createQuest    ( 32202 )
	createEntry    ( 32202, -1, 32198, {}, nil )
	createEntry    ( 32202, -1, 32199, {}, nil )
	createEntry    ( 32202, -1, 32200, {}, nil )
	createQuest    ( 27561 )
	createEntry    ( 27561, -1, 27180, {}, nil )
	createEntry    ( 27561, -1, 27181, {}, nil )
	createQuest    ( 32218 )
	createEntry    ( 32218, -1, 15772, {}, nil )
	createQuest    ( 57689 )
	createEntry    ( 57689, -1, 50224, {}, 176 )
	createEntry    ( 57689, -1, 50296, {}, 176 )
	createEntry    ( 57689, -1, 57690, {}, 176 )
	createEntry    ( 57689, -1, 57691, {}, 176 )
	createEntry    ( 57689, -1, 57692, {}, 176 )
	createEntry    ( 57689, -1, 61933, {}, 176 )
	createEntry    ( 57689, -1, 61934, {}, 176 )
	createEntry    ( 57689, -1, 61938, {}, 176 )
	createEntry    ( 57689, -1, 61939, {}, 176 )
	createEntry    ( 57689, -1, 60863, {}, 176 )
	createEntry    ( 57689, -1, 50131, {}, 176 )
	createEntry    ( 57689, -1, 68882, {}, 176 )
	createEntry    ( 57689, -1, 69023, {}, 176 )
	createEntry    ( 57689, -1, 66986, {}, 176 )
	createQuest    ( 58034 )
	createEntry    ( 58034, -1, 58035, {}, 177 )
	createEntry    ( 58034, -1, 58036, {}, 177 )
	createEntry    ( 58034, -1, 58037, {}, 177 )
	createEntry    ( 58034, -1, 58038, {}, 177 )
	createQuest    ( 58697 )
	createEntry    ( 58697, -1, 58698, {}, 178 )
	createEntry    ( 58697, -1, 58699, {}, 178 )
	createEntry    ( 58697, -1, 58700, {}, 178 )
	createEntry    ( 58697, -1, 58701, {}, 178 )
	createEntry    ( 58697, -1, 58702, {}, 178 )
	createEntry    ( 58697, -1, 58703, {}, 178 )
	createEntry    ( 58697, -1, 58704, {}, 178 )
	createEntry    ( 58697, -1, 58705, {}, 178 )
	createQuest    ( 58713 )
	createEntry    ( 58713, -1, 58714, {}, 179 )
	createEntry    ( 58713, -1, 58715, {}, 179 )
	createEntry    ( 58713, -1, 58716, {}, 179 )
	createEntry    ( 58713, -1, 58717, {}, 179 )
	createEntry    ( 58713, -1, 58718, {}, 179 )
	createEntry    ( 58713, -1, 58719, {}, 179 )
	createEntry    ( 58713, -1, 58720, {}, 179 )
	createEntry    ( 58713, -1, 58721, {}, 179 )
	createEntry    ( 58713, -1, 58722, {}, 179 )
	createEntry    ( 58713, -1, 58723, {}, 179 )
	createEntry    ( 58713, -1, 58789, {}, 179 )
	createEntry    ( 58713, -1, 58790, {}, 179 )
	createQuest    ( 58806 )
	createEntry    ( 58806, -1, 58807, {}, 180 )
	createEntry    ( 58806, -1, 58808, {}, 180 )
	createEntry    ( 58806, -1, 58809, {}, 180 )
	createEntry    ( 58806, -1, 58810, {}, 180 )
	createEntry    ( 58806, -1, 58811, {}, 180 )
	createEntry    ( 58806, -1, 58822, {}, 180 )
	createQuest    ( 59541 )
	createEntry    ( 59541, -1, 59542, {}, 181 )
	createEntry    ( 59541, -1, 59543, {}, 181 )
	createEntry    ( 59541, -1, 59544, {}, 181 )
	createEntry    ( 59541, -1, 59545, {}, 181 )
	createEntry    ( 59541, -1, 59546, {}, 181 )
	createEntry    ( 59541, -1, 59547, {}, 181 )
	createEntry    ( 59541, -1, 59548, {}, 181 )
	createEntry    ( 59541, -1, 59549, {}, 181 )
	createEntry    ( 59541, -1, 59550, {}, 181 )
	createEntry    ( 59541, -1, 59551, {}, 181 )
	createEntry    ( 59541, -1, 59552, {}, 181 )
	createEntry    ( 59541, -1, 59553, {}, 181 )
	createEntry    ( 59541, -1, 59554, {}, 181 )
	createEntry    ( 59541, -1, 59555, {}, 181 )
	createEntry    ( 59541, -1, 59556, {}, 181 )
	createEntry    ( 59541, -1, 59557, {}, 181 )
	createEntry    ( 59541, -1, 59558, {}, 181 )
	createEntry    ( 59541, -1, 59559, {}, 181 )
	createEntry    ( 59541, -1, 59560, {}, 181 )
	createEntry    ( 59541, -1, 59561, {}, 181 )
	createEntry    ( 59541, -1, 59562, {}, 181 )
	createEntry    ( 59541, -1, 59563, {}, 181 )
	createEntry    ( 59541, -1, 70637, {}, 181 )
	createEntry    ( 59541, -1, 71120, {}, 181 )
	createQuest    ( 59567 )
	createQuest    ( 59568 )
	createEntry    ( 59568, -1, 56383, {}, 183 )
	createEntry    ( 59568, -1, 56384, {}, 183 )
	createEntry    ( 59568, -1, 59574, {}, 183 )
	createEntry    ( 59568, -1, 59575, {}, 183 )
	createQuest    ( 59569 )
	createEntry    ( 59569, -1, 66937, {}, 184 )
	createEntry    ( 59569, -1, 56386, {}, 184 )
	createEntry    ( 59569, -1, 59571, {}, 184 )
	createQuest    ( 59615 )
	createEntry    ( 59615, -1, 66861, {}, 185 )
	createQuest    ( 59618 )
	createEntry    ( 59618, -1, 59625, {}, 186 )
	createEntry    ( 59618, -1, 67494, {}, 186 )
	createEntry    ( 59618, -1, 61580, {}, 186 )
	createEntry    ( 59618, -1, 61581, {}, 186 )
	createEntry    ( 59618, -1, 61582, {}, 186 )
	createEntry    ( 59618, -1, 61583, {}, 186 )
	createEntry    ( 59618, -1, 61584, {}, 186 )
	createEntry    ( 59618, -1, 61585, {}, 186 )
	createEntry    ( 59618, -1, 61586, {}, 186 )
	createEntry    ( 59618, -1, 61587, {}, 186 )
	createEntry    ( 59618, -1, 64854, {}, 186 )
	createEntry    ( 59618, -1, 61588, {}, 186 )
	createEntry    ( 59618, -1, 61589, {}, 186 )
	createEntry    ( 59618, -1, 61590, {}, 186 )
	createEntry    ( 59618, -1, 61591, {}, 186 )
	createQuest    ( 59620 )
	createEntry    ( 59620, -1, 56388, {}, 187 )
	createEntry    ( 59620, -1, 56390, {}, 187 )
	createEntry    ( 59620, -1, 59627, {}, 187 )
	createEntry    ( 59620, -1, 59856, {}, 187 )
	createEntry    ( 59620, -1, 61558, {}, 187 )
	createEntry    ( 59620, -1, 67018, {}, 187 )
	createEntry    ( 59620, -1, 67037, {}, 187 )
	createEntry    ( 59620, -1, 67061, {}, 187 )
	createEntry    ( 59620, -1, 66144, {}, 187 )
	createEntry    ( 59620, -1, 66145, {}, 187 )
	createQuest    ( 59621 )
	createEntry    ( 59621, -1, 59622, {}, 188 )
	createEntry    ( 59621, -1, 59633, {}, 188 )
	createEntry    ( 59621, -1, 67285, {}, 188 )
	createQuest    ( 59623 )
	createQuest    ( 59626 )
	createEntry    ( 59626, -1, 52704, {}, 190 )
	createEntry    ( 59626, -1, 59774, {}, 190 )
	createEntry    ( 59626, -1, 59854, {}, 190 )
	createEntry    ( 59626, -1, 59857, {}, 190 )
	createEntry    ( 59626, -1, 59859, {}, 190 )
	createEntry    ( 59626, -1, 67031, {}, 190 )
	createEntry    ( 59626, -1, 67057, {}, 190 )
	createEntry    ( 59626, -1, 67091, {}, 190 )
	createEntry    ( 59626, -1, 69814, {}, 190 )
	createEntry    ( 59626, -1, 69815, {}, 190 )
	createEntry    ( 59626, -1, 69816, {}, 190 )
	createQuest    ( 59645 )
	createEntry    ( 59645, -1, 49449, {}, 192 )
	createEntry    ( 59645, -1, 59646, {}, 192 )
	createEntry    ( 59645, -1, 43538, {}, 192 )
	createQuest    ( 59711 )
	createEntry    ( 59711, -1, 66864, {}, 195 )
	createQuest    ( 59716 )
	createEntry    ( 59716, -1, 56506, {}, 198 )
	createEntry    ( 59716, -1, 56520, {}, 198 )
	createEntry    ( 59716, -1, 56522, {}, 198 )
	createQuest    ( 59717 )
	createEntry    ( 59717, -1, 59786, {}, 199 )
	createEntry    ( 59717, -1, 59787, {}, 199 )
	createQuest    ( 59718 )
	createEntry    ( 59718, -1, 56787, {}, 200 )
	createEntry    ( 59718, -1, 56788, {}, 200 )
	createEntry    ( 59718, -1, 60182, {}, 200 )
	createQuest    ( 59732 )
	createEntry    ( 59732, -1, 66907, {}, 201 )
	createQuest    ( 59722 )
	createEntry    ( 59722, -1, 66909, {}, 202 )
	createQuest    ( 59731 )
	createEntry    ( 59731, -1, 59831, {}, 203 )
	createEntry    ( 59731, -1, 59832, {}, 203 )
	createEntry    ( 59731, -1, 59833, {}, 203 )
	createEntry    ( 59731, -1, 59834, {}, 203 )
	createEntry    ( 59731, -1, 59835, {}, 203 )
	createEntry    ( 59731, -1, 59836, {}, 203 )
	createEntry    ( 59731, -1, 59837, {}, 203 )
	createEntry    ( 59731, -1, 59838, {}, 203 )
	createEntry    ( 59731, -1, 59839, {}, 203 )
	createEntry    ( 59731, -1, 59840, {}, 203 )
	createEntry    ( 59731, -1, 59841, {}, 203 )
	createEntry    ( 59731, -1, 59842, {}, 203 )
	createEntry    ( 59731, -1, 59843, {}, 203 )
	createEntry    ( 59731, -1, 59844, {}, 203 )
	createEntry    ( 59731, -1, 59845, {}, 203 )
	createEntry    ( 59731, -1, 59882, {}, 203 )
	createEntry    ( 59731, -1, 69987, {}, 203 )
	createEntry    ( 59731, -1, 69988, {}, 203 )
	createQuest    ( 59734 )
	createEntry    ( 59734, -1, 59860, {}, 204 )
	createEntry    ( 59734, -1, 59861, {}, 204 )
	createEntry    ( 59734, -1, 59862, {}, 204 )
	createEntry    ( 59734, -1, 59863, {}, 204 )
	createEntry    ( 59734, -1, 65183, {}, 204 )
	createEntry    ( 59734, -1, 65184, {}, 204 )
	createEntry    ( 59734, -1, 66910, {}, 204 )
	createEntry    ( 59734, -1, 59865, {}, 204 )
	createEntry    ( 59734, -1, 69838, {}, 204 )
	createEntry    ( 59734, -1, 69867, {}, 204 )
	createQuest    ( 60258 )
	createEntry    ( 60258, -1, 60259, {}, 205 )
	createEntry    ( 60258, -1, 60262, {}, 205 )
	createEntry    ( 60258, -1, 60267, {}, 205 )
	createEntry    ( 60258, -1, 60273, {}, 205 )
	createEntry    ( 60258, -1, 60274, {}, 205 )
	createEntry    ( 60258, -1, 60278, {}, 205 )
	createEntry    ( 60258, -1, 60281, {}, 205 )
	createEntry    ( 60258, -1, 60284, {}, 205 )
	createEntry    ( 60258, -1, 69611, {}, 205 )
	createQuest    ( 61101 )
	createEntry    ( 61101, -1, 52026, {}, 206 )
	createEntry    ( 61101, -1, 52028, {}, 206 )
	createEntry    ( 61101, -1, 52030, {}, 206 )
	createEntry    ( 61101, -1, 52031, {}, 206 )
	createEntry    ( 61101, -1, 52034, {}, 206 )
	createEntry    ( 61101, -1, 52037, {}, 206 )
	createEntry    ( 61101, -1, 52038, {}, 206 )
	createEntry    ( 61101, -1, 52039, {}, 206 )
	createEntry    ( 61101, -1, 52042, {}, 206 )
	createEntry    ( 61101, -1, 52043, {}, 206 )
	createEntry    ( 61101, -1, 52044, {}, 206 )
	createEntry    ( 61101, -1, 52047, {}, 206 )
	createEntry    ( 61101, -1, 52048, {}, 206 )
	createEntry    ( 61101, -1, 52049, {}, 206 )
	createEntry    ( 61101, -1, 60204, {}, 206 )
	createEntry    ( 61101, -1, 70529, {}, 206 )
	createEntry    ( 61101, -1, 70627, {}, 206 )
	createEntry    ( 61101, -1, 70626, {}, 206 )	
	createEntry    ( 61101, -1, 71134, {}, 206 )
	createEntry    ( 61101, -1, 71136, {}, 206 )
	createEntry    ( 61101, -1, 71138, {}, 206 )
	createEntry    ( 61101, -1, 71141, {}, 206 )
	createEntry    ( 61101, -1, 52040, {}, 206 )
	createEntry    ( 61101, -1, 52041, {}, 206 )
	createQuest    ( 61301 )
	createEntry    ( 61301, -1, 61296, {}, 207 )
	createEntry    ( 61301, -1, 61297, {}, 207 )
	createEntry    ( 61301, -1, 61298, {}, 207 )
	createEntry    ( 61301, -1, 61299, {}, 207 )
	createEntry    ( 61301, -1, 61300, {}, 207 )
	createQuest    ( 61432 )
	createEntry    ( 61432, -1, 61433, {}, 208 )
	createEntry    ( 61432, -1, 61434, {}, 208 )
	createEntry    ( 61432, -1, 61435, {}, 208 )
	createEntry    ( 61432, -1, 61436, {}, 208 )
	createEntry    ( 61432, -1, 61437, {}, 208 )
	createEntry    ( 61432, -1, 61438, {}, 208 )
	createEntry    ( 61432, -1, 61439, {}, 208 )
	createEntry    ( 61432, -1, 61440, {}, 208 )
	createEntry    ( 61432, -1, 61441, {}, 208 )
	createEntry    ( 61432, -1, 61447, {}, 208 )
	createEntry    ( 61432, -1, 61448, {}, 208 )
	createEntry    ( 61432, -1, 61458, {}, 208 )
	createEntry    ( 61432, -1, 61459, {}, 208 )
	createEntry    ( 61432, -1, 61476, {}, 208 )
	createEntry    ( 61432, -1, 61477, {}, 208 )
	createEntry    ( 61432, -1, 61478, {}, 208 )
	createEntry    ( 61432, -1, 66967, {}, 208 )
	createEntry    ( 61432, -1, 67065, {}, 208 )
	createQuest    ( 61449 )
	createEntry    ( 61449, -1, 61450, {}, 209 )
	createEntry    ( 61449, -1, 61451, {}, 209 )
	createEntry    ( 61449, -1, 61452, {}, 209 )
	createEntry    ( 61449, -1, 61453, {}, 209 )
	createEntry    ( 61449, -1, 61454, {}, 209 )
	createEntry    ( 61449, -1, 61455, {}, 209 )
	createEntry    ( 61449, -1, 66970, {}, 209 )
	createEntry    ( 61449, -1, 70426, {}, 209 )
	createEntry    ( 61449, -1, 70427, {}, 209 )
	createQuest    ( 61502 )
	createEntry    ( 61502, -1, 61501, {}, 210 )
	createEntry    ( 61502, -1, 61509, {}, 210 )
	createEntry    ( 61502, -1, 61510, {}, 210 )
	createEntry    ( 61502, -1, 61511, {}, 210 )
	createEntry    ( 61502, -1, 67129, {}, 210 )
	createEntry    ( 61502, -1, 67131, {}, 210 )
	createEntry    ( 61502, -1, 70428, {}, 210 )
	createQuest    ( 61529 )
	createEntry    ( 61529, -1, 61530, {}, 211 )
	createEntry    ( 61529, -1, 61531, {}, 211 )
	createEntry    ( 61529, -1, 61532, {}, 211 )
	createEntry    ( 61529, -1, 61536, {}, 211 )
	createEntry    ( 61529, -1, 61537, {}, 211 )
	createEntry    ( 61529, -1, 61538, {}, 211 )
	createEntry    ( 61529, -1, 67081, {}, 211 )
	createQuest    ( 61592 )
	createEntry    ( 61592, -1, 61593, {}, 212 )
	createEntry    ( 61592, -1, 61594, {}, 212 )
	createEntry    ( 61592, -1, 61595, {}, 212 )
	createEntry    ( 61592, -1, 61596, {}, 212 )
	createQuest    ( 61597 )
	createEntry    ( 61597, -1, 61598, {}, 213 )
	createEntry    ( 61597, -1, 61599, {}, 213 )
	createEntry    ( 61597, -1, 61600, {}, 213 )
	createEntry    ( 61597, -1, 61601, {}, 213 )
	createEntry    ( 61597, -1, 61602, {}, 213 )
	createEntry    ( 61597, -1, 61603, {}, 213 )
	createQuest    ( 61604 )
	createEntry    ( 61604, -1, 61554, {}, 214 )
	createEntry    ( 61604, -1, 61605, {}, 214 )
	createEntry    ( 61604, -1, 67495, {}, 214 )
	createEntry    ( 61604, -1, 61606, {}, 214 )
	createEntry    ( 61604, -1, 61607, {}, 214 )
	createEntry    ( 61604, -1, 61608, {}, 214 )
	createEntry    ( 61604, -1, 61609, {}, 214 )
	createEntry    ( 61604, -1, 61610, {}, 214 )
	createQuest    ( 61611 )
	createEntry    ( 61611, -1, 55836, {}, 215 )
	createEntry    ( 61611, -1, 55838, {}, 215 )
	createEntry    ( 61611, -1, 55841, {}, 215 )
	createEntry    ( 61611, -1, 55842, {}, 215 )
	createQuest    ( 61612 )
	createEntry    ( 61612, -1, 45220, {}, 216 )
	createEntry    ( 61612, -1, 45221, {}, 216 )
	createEntry    ( 61612, -1, 45222, {}, 216 )
	createEntry    ( 61612, -1, 45223, {}, 216 )
	createEntry    ( 61612, -1, 45224, {}, 216 )
	createEntry    ( 61612, -1, 45225, {}, 216 )
	createEntry    ( 61612, -1, 45226, {}, 216 )
	createEntry    ( 61612, -1, 45229, {}, 216 )
	createEntry    ( 61612, -1, 45248, {}, 216 )
	createEntry    ( 61612, -1, 45249, {}, 216 )
	createEntry    ( 61612, -1, 45253, {}, 216 )
	createEntry    ( 61612, -1, 45254, {}, 216 )
	createEntry    ( 61612, -1, 45255, {}, 216 )
	createEntry    ( 61612, -1, 45256, {}, 216 )
	createEntry    ( 61612, -1, 45257, {}, 216 )
	createEntry    ( 61612, -1, 45260, {}, 216 )
	createEntry    ( 61612, -1, 45261, {}, 216 )
	createEntry    ( 61612, -1, 45262, {}, 216 )
	createEntry    ( 61612, -1, 61577, {}, 216 )
	createEntry    ( 61612, -1, 61613, {}, 216 )
	createEntry    ( 61612, -1, 61614, {}, 216 )
	createEntry    ( 61612, -1, 61615, {}, 216 )
	createEntry    ( 61612, -1, 61616, {}, 216 )
	createQuest    ( 61617 )
	createEntry    ( 61617, -1, 45475, {}, 217 )
	createEntry    ( 61617, -1, 45476, {}, 217 )
	createEntry    ( 61617, -1, 45487, {}, 217 )
	createEntry    ( 61617, -1, 55866, {}, 217 )
	createQuest    ( 61618 )
	createEntry    ( 61618, -1, 55867, {}, 218 )
	createEntry    ( 61618, -1, 55868, {}, 218 )
	createEntry    ( 61618, -1, 55869, {}, 218 )
	createEntry    ( 61618, -1, 55870, {}, 218 )
	createEntry    ( 61618, -1, 55871, {}, 218 )
	createQuest    ( 61625 )
	createEntry    ( 61625, -1, 61626, {}, 219 )
	createEntry    ( 61625, -1, 61627, {}, 219 )
	createQuest    ( 61628 )
	createEntry    ( 61628, -1, 61629, {}, 220 )
	createEntry    ( 61628, -1, 61631, {}, 220 )
	createEntry    ( 61628, -1, 61632, {}, 220 )
	createQuest    ( 61630 )
	createEntry    ( 61630, -1, 61633, {}, 221 )
	createEntry    ( 61630, -1, 61634, {}, 221 )
	createEntry    ( 61630, -1, 61635, {}, 221 )
	createEntry    ( 61630, -1, 61730, {}, 221 )
	createQuest    ( 61636 )
	createQuest    ( 61650 )
	createEntry    ( 61650, -1, 61651, {}, 223 )
	createEntry    ( 61650, -1, 61652, {}, 223 )
	createQuest    ( 61653 )
	createEntry    ( 61653, -1, 61654, {}, 224 )
	createEntry    ( 61653, -1, 61655, {}, 224 )
	createEntry    ( 61653, -1, 61656, {}, 224 )
	createEntry    ( 61653, -1, 61657, {}, 224 )
	createEntry    ( 61653, -1, 61658, {}, 224 )
	createEntry    ( 61653, -1, 61659, {}, 224 )
	createEntry    ( 61653, -1, 61660, {}, 224 )
	createEntry    ( 61653, -1, 61661, {}, 224 )
	createEntry    ( 61653, -1, 61662, {}, 224 )
	createQuest    ( 61663 )
	createEntry    ( 61663, -1, 61664, {}, 225 )
	createEntry    ( 61663, -1, 61665, {}, 225 )
	createEntry    ( 61663, -1, 61666, {}, 225 )
	createEntry    ( 61663, -1, 61667, {}, 225 )
	createEntry    ( 61663, -1, 61668, {}, 225 )
	createQuest    ( 61669 )
	createEntry    ( 61669, -1, 61670, {}, 226 )
	createEntry    ( 61669, -1, 61671, {}, 226 )
	createEntry    ( 61669, -1, 61672, {}, 226 )
	createEntry    ( 61669, -1, 61673, {}, 226 )
	createEntry    ( 61669, -1, 61674, {}, 226 )
	createEntry    ( 61669, -1, 61675, {}, 226 )
	createEntry    ( 61669, -1, 67429, {}, 226 )
	createQuest    ( 61676 )
	createEntry    ( 61676, -1, 61677, {}, 227 )
	createEntry    ( 61676, -1, 61678, {}, 227 )
	createEntry    ( 61676, -1, 61679, {}, 227 )
	createEntry    ( 61676, -1, 61680, {}, 227 )
	createEntry    ( 61676, -1, 65504, {}, 227 )
	createQuest    ( 61681 )
	createEntry    ( 61681, -1, 61682, {}, 228 )
	createEntry    ( 61681, -1, 61683, {}, 228 )
	createEntry    ( 61681, -1, 61684, {}, 228 )
	createEntry    ( 61681, -1, 61685, {}, 228 )
	createQuest    ( 61686 )
	createEntry    ( 61686, -1, 61687, {}, 229 )
	createEntry    ( 61686, -1, 61688, {}, 229 )
	createEntry    ( 61686, -1, 61689, {}, 229 )
	createEntry    ( 61686, -1, 61690, {}, 229 )
	createEntry    ( 61686, -1, 61691, {}, 229 )
	createEntry    ( 61686, -1, 61692, {}, 229 )
	createQuest    ( 61693 )
	createEntry    ( 61693, -1, 61569, {}, 230 )
	createEntry    ( 61693, -1, 69086, {}, 230 )
	createEntry    ( 61693, -1, 61694, {}, 230 )
	createEntry    ( 61693, -1, 61695, {}, 230 )
	createEntry    ( 61693, -1, 62618, {}, 230 )
	createQuest    ( 61696 )
	createEntry    ( 61696, -1, 61697, {}, 231 )
	createEntry    ( 61696, -1, 61698, {}, 231 )
	createEntry    ( 61696, -1, 61699, {}, 231 )
	createEntry    ( 61696, -1, 61700, {}, 231 )
	createQuest    ( 61707 )
	createEntry    ( 61707, -1, 49289, {}, 232 )
	createEntry    ( 61707, -1, 49290, {}, 232 )
	createEntry    ( 61707, -1, 49291, {}, 232 )
	createEntry    ( 61707, -1, 49292, {}, 232 )
	createEntry    ( 61707, -1, 61967, {}, 232 )
	createEntry    ( 61707, -1, 69688, {}, 232 )
	createQuest    ( 61708 )
	createEntry    ( 61708, -1, 61709, {}, 233 )
	createEntry    ( 61708, -1, 61710, {}, 233 )
	createEntry    ( 61708, -1, 61711, {}, 233 )
	createEntry    ( 61708, -1, 61712, {}, 233 )
	createEntry    ( 61708, -1, 61713, {}, 233 )
	createEntry    ( 61708, -1, 61714, {}, 233 )
	createEntry    ( 61708, -1, 61715, {}, 233 )
	createEntry    ( 61708, -1, 61716, {}, 233 )
	createEntry    ( 61708, -1, 61717, {}, 233 )
	createEntry    ( 61708, -1, 61966, {}, 233 )
	createEntry    ( 61708, -1, 47290, {}, 233 )
	createEntry    ( 61708, -1, 66965, {}, 233 )
	createEntry    ( 61708, -1, 66966, {}, 233 )
	createQuest    ( 61718 )
	createEntry    ( 61718, -1, 45609, {}, 234 )
	createEntry    ( 61718, -1, 45610, {}, 234 )
	createEntry    ( 61718, -1, 56070, {}, 234 )
	createEntry    ( 61718, -1, 56242, {}, 234 )
	createEntry    ( 61718, -1, 61719, {}, 234 )
	createEntry    ( 61718, -1, 62594, {}, 234 )
	createEntry    ( 61718, -1, 62595, {}, 234 )
	createEntry    ( 61718, -1, 62596, {}, 234 )
	createEntry    ( 61718, -1, 62597, {}, 234 )
	createEntry    ( 61718, -1, 62598, {}, 234 )
	createQuest    ( 61720 )
	createEntry    ( 61720, -1, 61721, {}, 235 )
	createEntry    ( 61720, -1, 62421, {}, 235 )
	createEntry    ( 61720, -1, 62422, {}, 235 )
	createEntry    ( 61720, -1, 62482, {}, 235 )
	createEntry    ( 61720, -1, 61722, {}, 235 )
	createEntry    ( 61720, -1, 61723, {}, 235 )
	createEntry    ( 61720, -1, 61724, {}, 235 )
	createEntry    ( 61720, -1, 66866, {}, 235 )
	createEntry    ( 61720, -1, 61725, {}, 235 )
	createEntry    ( 61720, -1, 61726, {}, 235 )
	createEntry    ( 61720, -1, 61727, {}, 235 )
	createEntry    ( 61720, -1, 61728, {}, 235 )
	createEntry    ( 61720, -1, 61729, {}, 235 )
	createEntry    ( 61720, -1, 66867, {}, 235 )
	createQuest    ( 61737 )
	createEntry    ( 61737, -1, 43431, {}, 236 )
	createEntry    ( 61737, -1, 49445, {}, 236 )
	createEntry    ( 61737, -1, 49448, {}, 236 )
	createEntry    ( 61737, -1, 49451, {}, 236 )
	createEntry    ( 61737, -1, 49452, {}, 236 )
	createEntry    ( 61737, -1, 61739, {}, 236 )
	createEntry    ( 61737, -1, 43520, {}, 236 )
	createEntry    ( 61737, -1, 57024, {}, 236 )
	createQuest    ( 61740 )
	createEntry    ( 61740, -1, 61741, {}, 237 )
	createEntry    ( 61740, -1, 61742, {}, 237 )
	createEntry    ( 61740, -1, 61743, {}, 237 )
	createEntry    ( 61740, -1, 61744, {}, 237 )
	createEntry    ( 61740, -1, 61745, {}, 237 )
	createEntry    ( 61740, -1, 61746, {}, 237 )
	createQuest    ( 61747 )
	createQuest    ( 61764 )
	createEntry    ( 61764, -1, 61765, {}, 239 )
	createEntry    ( 61764, -1, 61766, {}, 239 )
	createEntry    ( 61764, -1, 61767, {}, 239 )
	createEntry    ( 61764, -1, 61768, {}, 239 )
	createQuest    ( 61770 )
	createEntry    ( 61770, -1, 61772, {}, 240 )
	createEntry    ( 61770, -1, 61773, {}, 240 )
	createQuest    ( 61774 )
	createEntry    ( 61774, -1, 50671, {}, 241 )
	createEntry    ( 61774, -1, 57235, {}, 241 )
	createEntry    ( 61774, -1, 57236, {}, 241 )
	createEntry    ( 61774, -1, 57237, {}, 241 )
	createEntry    ( 61774, -1, 57238, {}, 241 )
	createEntry    ( 61774, -1, 57239, {}, 241 )
	createEntry    ( 61774, -1, 57240, {}, 241 )
	createEntry    ( 61774, -1, 57242, {}, 241 )
	createEntry    ( 61774, -1, 57244, {}, 241 )
	createEntry    ( 61774, -1, 61775, {}, 241 )
	createEntry    ( 61774, -1, 61776, {}, 241 )
	createEntry    ( 61774, -1, 67112, {}, 241 )
	createEntry    ( 61774, -1, 67461, {}, 241 )
	createEntry    ( 61774, -1, 67462, {}, 241 )
	createEntry    ( 61774, -1, 67463, {}, 241 )
	createQuest    ( 61777 )
	createEntry    ( 61777, -1, 50513, {}, 242 )
	createEntry    ( 61777, -1, 50518, {}, 242 )
	createEntry    ( 61777, -1, 50519, {}, 242 )
	createEntry    ( 61777, -1, 50521, {}, 242 )
	createEntry    ( 61777, -1, 50531, {}, 242 )
	createEntry    ( 61777, -1, 50532, {}, 242 )
	createEntry    ( 61777, -1, 50533, {}, 242 )
	createEntry    ( 61777, -1, 50534, {}, 242 )
	createEntry    ( 61777, -1, 50535, {}, 242 )
	createEntry    ( 61777, -1, 50536, {}, 242 )
	createEntry    ( 61777, -1, 50537, {}, 242 )
	createEntry    ( 61777, -1, 50780, {}, 242 )
	createEntry    ( 61777, -1, 50781, {}, 242 )
	createEntry    ( 61777, -1, 69503, {}, 242 )
	createEntry    ( 61777, -1, 69504, {}, 242 )
	createEntry    ( 61777, -1, 56832, {}, 242 )
	createEntry    ( 61777, -1, 70020, {}, 242 )
	createEntry    ( 61777, -1, 70021, {}, 242 )
	createQuest    ( 61778 )
	createEntry    ( 61778, -1, 50750, {}, 243 )
	createEntry    ( 61778, -1, 56833, {}, 243 )
	createEntry    ( 61778, -1, 56838, {}, 243 )
	createEntry    ( 61778, -1, 56839, {}, 243 )
	createEntry    ( 61778, -1, 56840, {}, 243 )
	createEntry    ( 61778, -1, 58558, {}, 243 )
	createQuest    ( 61853 )
	createEntry    ( 61853, -1, 61854, {}, 244 )
	createEntry    ( 61853, -1, 61855, {}, 244 )
	createEntry    ( 61853, -1, 61856, {}, 244 )
	createEntry    ( 61853, -1, 61857, {}, 244 )
	createEntry    ( 61853, -1, 61858, {}, 244 )
	createEntry    ( 61853, -1, 61859, {}, 244 )
	createEntry    ( 61853, -1, 61860, {}, 244 )
	createEntry    ( 61853, -1, 61861, {}, 244 )
	createEntry    ( 61853, -1, 61862, {}, 244 )
	createEntry    ( 61853, -1, 67083, {}, 244 )
	createQuest    ( 61863 )
	createEntry    ( 61863, -1, 58633, {}, 245 )
	createEntry    ( 61863, -1, 58634, {}, 245 )
	createEntry    ( 61863, -1, 58635, {}, 245 )
	createEntry    ( 61863, -1, 58636, {}, 245 )
	createEntry    ( 61863, -1, 58637, {}, 245 )
	createEntry    ( 61863, -1, 58638, {}, 245 )
	createEntry    ( 61863, -1, 58639, {}, 245 )
	createEntry    ( 61863, -1, 58640, {}, 245 )
	createEntry    ( 61863, -1, 58641, {}, 245 )
	createEntry    ( 61863, -1, 58643, {}, 245 )
	createEntry    ( 61863, -1, 58644, {}, 245 )
	createEntry    ( 61863, -1, 61864, {}, 245 )
	createEntry    ( 61863, -1, 61865, {}, 245 )
	createEntry    ( 61863, -1, 67109, {}, 245 )
	createEntry    ( 61863, -1, 67110, {}, 245 )
	createEntry    ( 61863, -1, 61866, {}, 245 )
	createQuest    ( 61867 )
	createEntry    ( 61867, -1, 61868, {}, 246 )
	createEntry    ( 61867, -1, 61869, {}, 246 )
	createEntry    ( 61867, -1, 61870, {}, 246 )
	createEntry    ( 61867, -1, 61871, {}, 246 )
	createEntry    ( 61867, -1, 69691, {}, 246 )
	createQuest    ( 61872 )
	createEntry    ( 61872, -1, 61873, {}, 247 )
	createEntry    ( 61872, -1, 61874, {}, 247 )
	createEntry    ( 61872, -1, 61875, {}, 247 )
	createEntry    ( 61872, -1, 61876, {}, 247 )
	createEntry    ( 61872, -1, 61877, {}, 247 )
	createEntry    ( 61872, -1, 61878, {}, 247 )
	createEntry    ( 61872, -1, 61879, {}, 247 )
	createEntry    ( 61872, -1, 62460, {}, 247 )
	createQuest    ( 61880 )
	createEntry    ( 61880, -1, 47436, {}, 248 )
	createEntry    ( 61880, -1, 47437, {}, 248 )
	createEntry    ( 61880, -1, 47438, {}, 248 )
	createEntry    ( 61880, -1, 47439, {}, 248 )
	createEntry    ( 61880, -1, 47440, {}, 248 )
	createEntry    ( 61880, -1, 48432, {}, 248 )
	createEntry    ( 61880, -1, 49364, {}, 248 )
	createQuest    ( 61881 )
	createEntry    ( 61881, -1, 49357, {}, 249 )
	createEntry    ( 61881, -1, 61882, {}, 249 )
	createQuest    ( 61883 )
	createEntry    ( 61883, -1, 61884, {}, 250 )
	createEntry    ( 61883, -1, 61885, {}, 250 )
	createEntry    ( 61883, -1, 61886, {}, 250 )
	createEntry    ( 61883, -1, 61887, {}, 250 )
	--createQuest    ( 61888 )
	--createEntry    ( 61888, -1, 43891, {}, 251 )
	--createEntry    ( 61888, -1, 61916, {}, 251 )
	createQuest    ( 61889 )
	createEntry    ( 61889, -1, 43892, {}, 252 )
	createEntry    ( 61889, -1, 61929, {}, 252 )
	createEntry    ( 61889, -1, 61930, {}, 252 )
	createEntry    ( 61889, -1, 61931, {}, 252 )
	createEntry    ( 61889, -1, 61932, {}, 252 )
	createEntry    ( 61889, -1, 49405, {}, 252 )
	createEntry    ( 61889, -1, 49406, {}, 252 )
	createEntry    ( 61889, -1, 49407, {}, 252 )
	createEntry    ( 61889, -1, 49408, {}, 252 )
	createQuest    ( 61890 )
	createEntry    ( 61890, -1, 48435, {}, 253 )
	createQuest    ( 61891 )
	createEntry    ( 61891, -1, 40754, {}, 254 )
	createEntry    ( 61891, -1, 40755, {}, 254 )
	createEntry    ( 61891, -1, 40756, {}, 254 )
	createEntry    ( 61891, -1, 43894, {}, 254 )
	createEntry    ( 61891, -1, 61950, {}, 254 )
	createEntry    ( 61891, -1, 70628, {}, 254 )
	createEntry    ( 61891, -1, 70629, {}, 254 )
	createQuest    ( 61892 )
	createEntry    ( 61892, -1, 61518, {}, 255 )
	createEntry    ( 61892, -1, 61519, {}, 255 )
	createEntry    ( 61892, -1, 61520, {}, 255 )
	createEntry    ( 61892, -1, 61893, {}, 255 )
	createEntry    ( 61892, -1, 69594, {}, 255 )
	createEntry    ( 61892, -1, 69690, {}, 255 )
	createQuest    ( 61896 )
	createQuest    ( 61898 )
	createEntry    ( 61898, -1, 61899, {}, 257 )
	createEntry    ( 61898, -1, 61900, {}, 257 )
	createEntry    ( 61898, -1, 61901, {}, 257 )
	createEntry    ( 61898, -1, 61902, {}, 257 )
	createEntry    ( 61898, -1, 61903, {}, 257 )
	createEntry    ( 61898, -1, 61906, {}, 257 )
	createEntry    ( 61898, -1, 61907, {}, 257 )
	createEntry    ( 61898, -1, 61908, {}, 257 )
	createEntry    ( 61898, -1, 61909, {}, 257 )
	createEntry    ( 61898, -1, 69540, {}, 257 )
	createQuest    ( 61910 )
	createEntry    ( 61910, -1, 61911, {}, 258 )
	createEntry    ( 61910, -1, 61912, {}, 258 )
	createEntry    ( 61910, -1, 61913, {}, 258 )
	createQuest    ( 61914 )
	createEntry    ( 61914, -1, 65396, {}, 259 )
	createEntry    ( 61914, -1, 49283, {}, 259 )
	createEntry    ( 61914, -1, 65397, {}, 259 )
	createEntry    ( 61914, -1, 71122, {}, 259 )
	createQuest    ( 61915 )
	createEntry    ( 61915, -1, 40351, {}, 260 )
	createEntry    ( 61915, -1, 49285, {}, 260 )
	createEntry    ( 61915, -1, 49286, {}, 260 )
	createEntry    ( 61915, -1, 49329, {}, 260 )
	createEntry    ( 61915, -1, 49330, {}, 260 )
	createEntry    ( 61915, -1, 56976, {}, 260 )
	createEntry    ( 61915, -1, 69198, {}, 260 )
	createQuest    ( 61917 )
	createEntry    ( 61917, -1, 61918, {}, 261 )
	createEntry    ( 61917, -1, 61919, {}, 261 )
	createEntry    ( 61917, -1, 61920, {}, 261 )
	createEntry    ( 61917, -1, 61921, {}, 261 )
	createEntry    ( 61917, -1, 61922, {}, 261 )
	createEntry    ( 61917, -1, 61923, {}, 261 )
	createEntry    ( 61917, -1, 61924, {}, 261 )
	createEntry    ( 61917, -1, 61925, {}, 261 )
	createEntry    ( 61917, -1, 61926, {}, 261 )
	createEntry    ( 61917, -1, 61927, {}, 261 )
	createEntry    ( 61917, -1, 61928, {}, 261 )
	createEntry    ( 61917, -1, 69488, {}, 261 )
	createEntry    ( 61917, -1, 69489, {}, 261 )
	createEntry    ( 61917, -1, 69495, {}, 261 )
	createEntry    ( 61917, -1, 70420, {}, 261 )
	createEntry    ( 61917, -1, 71336, {}, 261 )
	createQuest    ( 61935 )
	createEntry    ( 61935, -1, 58041, {}, 262 )
	createEntry    ( 61935, -1, 58042, {}, 262 )
	createEntry    ( 61935, -1, 58043, {}, 262 )
	createQuest    ( 61940 )
	createEntry    ( 61940, -1, 61941, {}, 263 )
	createEntry    ( 61940, -1, 61942, {}, 263 )
	createEntry    ( 61940, -1, 61382, {}, 263 )
	createQuest    ( 61945 )
	createEntry    ( 61945, -1, 61946, {}, 264 )
	createEntry    ( 61945, -1, 61948, {}, 264 )
	createEntry    ( 61945, -1, 61949, {}, 264 )
	createEntry    ( 61945, -1, 66740, {}, 264 )
	createQuest    ( 61963 )
	createEntry    ( 61963, -1, 61964, {}, 265 )
	createEntry    ( 61963, -1, 61965, {}, 265 )
	createQuest    ( 62483 )
	createEntry    ( 62483, -1, 61738, {}, 266 )
	createEntry    ( 62483, -1, 67430, {}, 266 )
	createEntry    ( 62483, -1, 66015, {}, 266 )
	createEntry    ( 62483, -1, 66016, {}, 266 )
	createQuest    ( 49477 )
	createEntry    ( 49477, -1, 43891, {}, 267 )
	createEntry    ( 49477, -1, 49404, {}, 267 )
	createEntry    ( 49477, -1, 61916, {}, 267 )
	createQuest    ( 51953 )
	createEntry    ( 51953, -1, 51954, {}, 268 )
	createEntry    ( 51953, -1, 51955, {}, 268 )
	createEntry    ( 51953, -1, 51956, {}, 268 )
	createEntry    ( 51953, -1, 51957, {}, 268 )
	createEntry    ( 51953, -1, 58084, {}, 268 )
	createEntry    ( 51953, -1, 58085, {}, 268 )
	createEntry    ( 51953, -1, 58086, {}, 268 )
	createQuest    ( 49478 )	
	createQuest    ( 58475 )
	createEntry    ( 58475, -1, 58472, {}, 270 )
	createEntry    ( 58475, -1, 58473, {}, 270 )
	createEntry    ( 58475, -1, 58474, {}, 270 )
	createQuest    ( 64446 )
	createEntry    ( 64446, -1, 64440, {}, 271 )
	createEntry    ( 64446, -1, 64441, {}, 271 )
	createEntry    ( 64446, -1, 64442, {}, 271 )
	createEntry    ( 64446, -1, 64443, {}, 271 )
	createEntry    ( 64446, -1, 64444, {}, 271 )
	createEntry    ( 64446, -1, 64445, {}, 271 )
	createEntry    ( 64446, -1, 64641, {}, 271 )
	createEntry    ( 64446, -1, 64642, {}, 271 )
	createEntry    ( 64446, -1, 67302, {}, 271 )
	createQuest    ( 64506 )
	createEntry    ( 64506, -1, 64295, {}, 272 )
	createEntry    ( 64506, -1, 66956, {}, 272 )
	createQuest    ( 64473 )
	createEntry    ( 64473, -1, 64380, {}, 273 )
	createEntry    ( 64473, -1, 64402, {}, 273 )
	createEntry    ( 64473, -1, 64403, {}, 273 )
	createEntry    ( 64473, -1, 64404, {}, 273 )
	createEntry    ( 64473, -1, 64405, {}, 273 )
	createEntry    ( 64473, -1, 64406, {}, 273 )
	createEntry    ( 64473, -1, 64407, {}, 273 )
	createEntry    ( 64473, -1, 64408, {}, 273 )
	createEntry    ( 64473, -1, 64409, {}, 273 )
	createEntry    ( 64473, -1, 64411, {}, 273 )
	createEntry    ( 64473, -1, 64413, {}, 273 )
	createEntry    ( 64473, -1, 64414, {}, 273 )
	createEntry    ( 64473, -1, 64415, {}, 273 )
	createEntry    ( 64473, -1, 64416, {}, 273 )
	createEntry    ( 64473, -1, 64417, {}, 273 )
	createEntry    ( 64473, -1, 64418, {}, 273 )
	createEntry    ( 64473, -1, 64419, {}, 273 )
	createEntry    ( 64473, -1, 64420, {}, 273 )
	createEntry    ( 64473, -1, 64421, {}, 273 )
	createEntry    ( 64473, -1, 64422, {}, 273 )
	createEntry    ( 64473, -1, 64423, {}, 273 )
	createEntry    ( 64473, -1, 64424, {}, 273 )
	createEntry    ( 64473, -1, 64425, {}, 273 )
	createEntry    ( 64473, -1, 64426, {}, 273 )
	createEntry    ( 64473, -1, 64427, {}, 273 )
	createEntry    ( 64473, -1, 64428, {}, 273 )
	createEntry    ( 64473, -1, 64429, {}, 273 )
	createEntry    ( 64473, -1, 64430, {}, 273 )
	createEntry    ( 64473, -1, 64431, {}, 273 )
	createEntry    ( 64473, -1, 64432, {}, 273 )
	createEntry    ( 64473, -1, 64433, {}, 273 )
	createEntry    ( 64473, -1, 64434, {}, 273 )
	createEntry    ( 64473, -1, 64435, {}, 273 )
	createEntry    ( 64473, -1, 64436, {}, 273 )
	createEntry    ( 64473, -1, 64437, {}, 273 )
	createEntry    ( 64473, -1, 64438, {}, 273 )
	createEntry    ( 64473, -1, 64669, {}, 273 )
	createEntry    ( 64473, -1, 64670, {}, 273 )
	createEntry    ( 64473, -1, 64744, {}, 273 )
	createEntry    ( 64473, -1, 67500, {}, 273 )
	createQuest    ( 64981 )
	createEntry    ( 64981, -1, 66863, {}, 274 )
	createQuest    ( 64982 )
	createEntry    ( 64982, -1, 64983, {}, 275 )
	createEntry    ( 64982, -1, 64985, {}, 275 )
	createEntry    ( 64982, -1, 64986, {}, 275 )
	createEntry    ( 64982, -1, 64987, {}, 275 )
	createEntry    ( 64982, -1, 64988, {}, 275 )
	createEntry    ( 64982, -1, 64990, {}, 275 )
	createQuest    ( 69214 )
	createEntry    ( 69214, -1, 65605, {}, 276 )
	createEntry    ( 69214, -1, 66181, {}, 276 )
	createEntry    ( 69214, -1, 66182, {}, 276 )
	createEntry    ( 69214, -1, 66183, {}, 276 )
	createQuest    ( 66700 )
	createEntry    ( 66700, -1, 66701, {}, 277 )
	createQuest    ( 66743 )
	createEntry    ( 66743, -1, 66741, {}, 278 )
	createQuest    ( 67432 )
	createEntry    ( 67432, -1, 66745, {}, 279 )
	createQuest    ( 67432 )
	createEntry    ( 67432, -1, 59641, {}, 280 )
	createEntry    ( 67432, -1, 59642, {}, 280 )
	createQuest    ( 66957 )
	createEntry    ( 66957, -1, 64308, {}, 282 )
	createEntry    ( 66957, -1, 70022, {}, 282 )
	createEntry    ( 66957, -1, 70023, {}, 282 )
	createEntry    ( 66957, -1, 70024, {}, 282 )
	createEntry    ( 66957, -1, 70025, {}, 282 )
	createEntry    ( 66957, -1, 64311, {}, 282 )
	createEntry    ( 66957, -1, 64312, {}, 282 )
	createEntry    ( 66957, -1, 64314, {}, 282 )
	createEntry    ( 66957, -1, 64315, {}, 282 )
	createEntry    ( 66957, -1, 64317, {}, 282 )
	createQuest    ( 69686 )
	createEntry    ( 69686, -1, 59782, {}, 285 )
	createEntry    ( 69686, -1, 59783, {}, 285 )
	createEntry    ( 69686, -1, 59788, {}, 285 )
	createEntry    ( 69686, -1, 59789, {}, 285 )
	createEntry    ( 69686, -1, 69685, {}, 285 )
	createQuest    ( 71143 )
	createEntry    ( 71143, -1, 71135, {}, 286 )
	createEntry    ( 71143, -1, 71137, {}, 286 )
	createEntry    ( 71143, -1, 71139, {}, 286 )
	createEntry    ( 71143, -1, 71140, {}, 286 )
	createEntry    ( 71143, -1, 71142, {}, 286 )
end
