difficulties =
{
	{icon = "COLRSPRY", name = "DIFFICULTY_LABEL_STORYMODE", 		description = "DIFFICULTY_DESCRIPTION_STORYMODE`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTSHLF", name = "DIFFICULTY_LABEL_EASY", 			description = "DIFFICULTY_DESCRIPTION_EASY`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTSACK", name = "DIFFICULTY_LABEL_NORMAL", 			description = "DIFFICULTY_DESCRIPTION_NORMAL`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTGRND", name = "DIFFICULTY_LABEL_CORERULES", 		description = "DIFFICULTY_DESCRIPTION_CORERULES`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTBODY", name = "DIFFICULTY_LABEL_HARD", 			description = "DIFFICULTY_DESCRIPTION_HARD`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTSKL1", name = "DIFFICULTY_LABEL_INSANE", 			description = "DIFFICULTY_DESCRIPTION_INSANE`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
	{icon = "CONTSKL2", name = "DIFFICULTY_LABEL_LEGACYOFBHAAL", 	description = "DIFFICULTY_DESCRIPTION_LEGACYOFBHAAL`CHARGEN_DIFFICULTY_DESCRIPTION_SUFFIX`"},
}
fromSinglePlayer = false
fromMultiPlayer = false
function WhoYouGonnaCall()
	fromSinglePlayer = (createCharScreen:GetEngineState() == 1 or createCharScreen:GetEngineState() == 7) and multiplayerScreen:GetEngineState() ~= 1
end