	mouseOverPortrait = -1
	draggedPortrait = nil
	function swapPortraits(dest)
		worldScreen:SwapPortraits(dest,draggedPortrait)
		draggedPortrait = nil
	end

	function getPartyAITooltip()
		if aiButtonToggle == 1 then
			return Infinity_FetchString(15918)
		else
			return Infinity_FetchString(15917)
		end
	end

	function hidePortraits()
		--if LargePortraits == 1 then
			if Infinity_GetNumCharacters() == 1 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 2 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 3 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 4 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 5 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 6 and LargePortraits == 1 then
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 86, 131)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 82, 123)
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			end
		--else
			if Infinity_GetNumCharacters() == 1 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 2 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 3 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 4 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 5 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			elseif Infinity_GetNumCharacters() == 6 and LargePortraits == 0 then
			Infinity_SetArea('portrait1ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait1ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait2ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait2ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait3ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait3ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait4ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait4ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait5ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait5ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait6ShadowSmall', nil, nil, 68, 99)
			Infinity_SetArea('portrait6ButtonSmall', nil, nil, 64, 91)
			Infinity_SetArea('portrait1ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait1ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait2ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait3ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait4ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait5ButtonBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ShadowBig', nil, nil, 0, 0)
			Infinity_SetArea('portrait6ButtonBig', nil, nil, 0, 0)
			end
		--end
	end